"""Cover casting, colors, and mottoes for illustrated Legend Land guidebooks."""

META = {
    "eagles": {
        "file_title": "Philadelphia_Eagles",
        "display": "The Philadelphia Eagles",
        "colors_words": "midnight green, silver, white, and gold",
        "logo": "official Philadelphia Eagles eagle-head logo",
        "helmet": "midnight-green Eagles helmet with silver wings",
        "figures": "Andy Reid in an Eagles cap, Doug Pederson, and owner Jeffrey Lurie in dark suits",
        "players": "Steve Van Buren, Chuck Bednarik, Reggie White, Donovan McNabb, Jalen Hurts",
        "trophies": "1948 and 1949 NFL championship trophies plus the Super Bowl LII Lombardi Trophy",
        "motto": "FLY EAGLES FLY. HONOR THE BELL. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Eagles eagle-head marks, never Dallas Cowboys stars",
    },
    "cowboys": {
        "file_title": "Dallas_Cowboys",
        "display": "The Dallas Cowboys",
        "colors_words": "navy blue, silver, white, and metallic gold",
        "logo": "official Dallas Cowboys five-point navy-and-white star",
        "helmet": "silver Cowboys helmet with the blue-white star",
        "figures": "Tom Landry in his fedora, Jimmy Johnson, and Jerry Jones in dark suits",
        "players": "Roger Staubach, Troy Aikman, Michael Irvin, Emmitt Smith, Larry Allen",
        "trophies": "five Vince Lombardi trophies labeled VI, XII, XXVII, XXVIII, and XXX",
        "motto": "RESPECT THE STAR. HONOR THE PAST. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Cowboys stars and gold filigree",
    },
    "bills": {
        "file_title": "Buffalo_Bills",
        "display": "The Buffalo Bills",
        "colors_words": "royal blue, red, and white",
        "logo": "official Buffalo Bills charging-buffalo logo",
        "helmet": "red Bills helmet with the charging buffalo",
        "figures": "Ralph Wilson, Marv Levy, and Jim Kelly in period dress and suits",
        "players": "Jack Kemp, O.J. Simpson, Thurman Thomas, Bruce Smith, Josh Allen",
        "trophies": "1964 and 1965 AFL championship trophies and four AFC title trophies",
        "motto": "CHARGE THE STORM. HONOR THE MAFIA. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Bills charging-buffalo marks, never Dallas stars",
    },
    "dolphins": {
        "file_title": "Miami_Dolphins",
        "display": "The Miami Dolphins",
        "colors_words": "aqua, orange, white, and navy",
        "logo": "official Miami Dolphins sun-burst leaping-dolphin logo",
        "helmet": "white Dolphins helmet with the aqua-orange dolphin",
        "figures": "Joe Robbie, Don Shula, and Bob Griese in period dress and suits",
        "players": "Larry Csonka, Mercury Morris, Dan Marino, Jason Taylor, Tua Tagovailoa",
        "trophies": "Super Bowl VII and Super Bowl VIII Lombardi trophies",
        "motto": "PERFECT THE SEASON. HONOR THE AQUA. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Dolphins logos, never Dallas stars",
    },
    "jets": {
        "file_title": "New_York_Jets",
        "display": "The New York Jets",
        "colors_words": "Gotham green, white, and black",
        "logo": "official New York Jets wordmark jet-oval logo",
        "helmet": "green Jets helmet with the wordmark",
        "figures": "Weeb Ewbank, Joe Namath, and Bill Parcells",
        "players": "Joe Namath, Don Maynard, Joe Klecko, Curtis Martin, Darrelle Revis",
        "trophies": "the Super Bowl III Lombardi Trophy",
        "motto": "GUARANTEE THE WIN. HONOR BROADWAY. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Jets logos, never Dallas stars",
    },
    "patriots": {
        "file_title": "New_England_Patriots",
        "display": "The New England Patriots",
        "colors_words": "navy, silver, red, and white",
        "logo": "official New England Patriots Flying Elvis logo",
        "helmet": "silver Patriots helmet with the Flying Elvis",
        "figures": "Robert Kraft, Bill Belichick, and Bill Parcells",
        "players": "Babe Parilli, Drew Bledsoe, Tom Brady, Rob Gronkowski, Tedy Bruschi",
        "trophies": "six Lombardi trophies for Super Bowls XXXVI, XXXVIII, XXXIX, XLIX, LI, and LIII",
        "motto": "DO YOUR JOB. HONOR THE DYNASTY. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Patriots Flying Elvis marks, never Dallas stars",
    },
    "ravens": {
        "file_title": "Baltimore_Ravens",
        "display": "The Baltimore Ravens",
        "colors_words": "purple, black, metallic gold, and white",
        "logo": "official Baltimore Ravens shield-and-raven-head logo",
        "helmet": "purple Ravens helmet with the raven-head shield",
        "figures": "Art Modell, Ozzie Newsome, and John Harbaugh",
        "players": "Jonathan Ogden, Ray Lewis, Ed Reed, Joe Flacco, Lamar Jackson",
        "trophies": "Super Bowl XXXV and Super Bowl XLVII Lombardi trophies",
        "motto": "PROTECT THIS HOUSE. HONOR NEVERMORE. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Ravens shield marks, never Dallas stars",
    },
    "bengals": {
        "file_title": "Cincinnati_Bengals",
        "display": "The Cincinnati Bengals",
        "colors_words": "orange, black, and white",
        "logo": "official Cincinnati Bengals leaping-tiger B logo",
        "helmet": "orange tiger-stripe Bengals helmet",
        "figures": "Paul Brown, Marvin Lewis, and Zac Taylor",
        "players": "Anthony Munoz, Ken Anderson, Boomer Esiason, Chad Johnson, Joe Burrow",
        "trophies": "AFC championship trophies from Super Bowl XVI, XXIII, and LVI trips",
        "motto": "WHO DEY. HONOR THE STRIPES. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Bengals B logos and tiger stripes, never Dallas stars",
    },
    "browns": {
        "file_title": "Cleveland_Browns",
        "display": "The Cleveland Browns",
        "colors_words": "burnt orange, brown, white, and gray",
        "logo": "official Cleveland Browns helmet-shaped browns logo",
        "helmet": "plain orange Browns helmet with a brown-white stripe",
        "figures": "Paul Brown, Otto Graham, and Jim Brown",
        "players": "Marion Motley, Lou Groza, Jim Brown, Ozzie Newsome, Myles Garrett",
        "trophies": "AAFC and 1964 NFL championship trophies",
        "motto": "DAWG POUND. HONOR THE LAKE. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Browns helmet marks, never Dallas stars",
    },
    "steelers": {
        "file_title": "Pittsburgh_Steelers",
        "display": "The Pittsburgh Steelers",
        "colors_words": "black, gold, and white",
        "logo": "official Pittsburgh Steelers steel-mark hypocycloid logo",
        "helmet": "black Steelers helmet with the steel mark on one side",
        "figures": "Art Rooney, Chuck Noll, and Bill Cowher",
        "players": "Joe Greene, Terry Bradshaw, Jack Lambert, Franco Harris, Ben Roethlisberger",
        "trophies": "six Lombardi trophies for Super Bowls IX, X, XIII, XIV, XL, and XLIII",
        "motto": "HERE WE GO. HONOR THE MILL. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Steelers steel-mark logos, never Dallas stars",
    },
    "texans": {
        "file_title": "Houston_Texans",
        "display": "The Houston Texans",
        "colors_words": "deep steel blue, battle red, and white",
        "logo": "official Houston Texans bull-head logo",
        "helmet": "dark blue Texans helmet with the red-eyed bull",
        "figures": "Bob McNair, J.J. Watt, and DeMeco Ryans",
        "players": "Andre Johnson, J.J. Watt, Arian Foster, DeAndre Hopkins, C.J. Stroud",
        "trophies": "AFC South championship trophies",
        "motto": "BULL UP. HONOR HOUSTON. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Texans bull marks, never Dallas stars",
    },
    "colts": {
        "file_title": "Indianapolis_Colts",
        "display": "The Indianapolis Colts",
        "colors_words": "royal blue, white, and silver",
        "logo": "official Indianapolis Colts horseshoe logo",
        "helmet": "white Colts helmet with the blue horseshoe",
        "figures": "Jim Irsay, Tony Dungy, and Peyton Manning",
        "players": "Johnny Unitas, Peyton Manning, Marvin Harrison, Edgerrin James, Dwight Freeney",
        "trophies": "Super Bowl V and Super Bowl XLI Lombardi trophies",
        "motto": "BLEED BLUE. HONOR THE HORSESHOE. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Colts horseshoes, never Dallas stars",
    },
    "jaguars": {
        "file_title": "Jacksonville_Jaguars",
        "display": "The Jacksonville Jaguars",
        "colors_words": "teal, black, gold, and white",
        "logo": "official Jacksonville Jaguars snarling-jaguar logo",
        "helmet": "black Jaguars helmet with the gold-teal jaguar",
        "figures": "Wayne Weaver, Tom Coughlin, and Trevor Lawrence",
        "players": "Tony Boselli, Mark Brunell, Jimmy Smith, Fred Taylor, Trevor Lawrence",
        "trophies": "1996 and 1999 AFC Championship trophies",
        "motto": "DUUUVAL. HONOR THE TEAL. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Jaguars jaguar marks, never Dallas stars",
    },
    "titans": {
        "file_title": "Tennessee_Titans",
        "display": "The Tennessee Titans",
        "colors_words": "navy, Titans blue, red, silver, and white",
        "logo": "official Tennessee Titans circle-and-flame T sword logo",
        "helmet": "navy Titans helmet with the flaming T",
        "figures": "Bud Adams, Jeff Fisher, and Steve McNair",
        "players": "Earl Campbell, Warren Moon, Eddie George, Steve McNair, Derrick Henry",
        "trophies": "AFL Oilers titles and the 1999 AFC championship trophy",
        "motto": "TITAN UP. HONOR LUV YA BLUE. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Titans flaming-T marks, never Dallas stars",
    },
    "broncos": {
        "file_title": "Denver_Broncos",
        "display": "The Denver Broncos",
        "colors_words": "orange, navy, and white",
        "logo": "official Denver Broncos horse-head logo",
        "helmet": "navy Broncos helmet with the orange horse head",
        "figures": "Pat Bowlen, Mike Shanahan, and John Elway",
        "players": "Floyd Little, John Elway, Terrell Davis, Champ Bailey, Von Miller",
        "trophies": "Super Bowl XXXII, XXXIII, and 50 Lombardi trophies",
        "motto": "RIDE THE HORSE. HONOR MILE HIGH. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Broncos horse-head marks, never Dallas stars",
    },
    "chiefs": {
        "file_title": "Kansas_City_Chiefs",
        "display": "The Kansas City Chiefs",
        "colors_words": "red, gold, and white",
        "logo": "official Kansas City Chiefs arrowhead logo",
        "helmet": "red Chiefs helmet with the white arrowhead",
        "figures": "Lamar Hunt, Hank Stram, and Andy Reid",
        "players": "Len Dawson, Derrick Thomas, Tony Gonzalez, Patrick Mahomes, Travis Kelce",
        "trophies": "Super Bowl IV, LIV, LVII, and LVIII Lombardi trophies",
        "motto": "CHOP ON. HONOR THE KINGDOM. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Chiefs arrowheads, never Dallas stars",
    },
    "raiders": {
        "file_title": "Las_Vegas_Raiders",
        "display": "The Las Vegas Raiders",
        "colors_words": "silver, black, and white",
        "logo": "official Raiders shield with the eye-patch raider",
        "helmet": "black Raiders helmet with the silver-black shield",
        "figures": "Al Davis, John Madden, and Tom Flores",
        "players": "Ken Stabler, Fred Biletnikoff, Marcus Allen, Howie Long, Tim Brown",
        "trophies": "Super Bowl XI, XV, and XVIII Lombardi trophies",
        "motto": "JUST WIN, BABY. COMMITMENT TO EXCELLENCE.",
        "border_motif": "repeating official Raiders shields, never Dallas stars",
    },
    "chargers": {
        "file_title": "Los_Angeles_Chargers",
        "display": "The Los Angeles Chargers",
        "colors_words": "powder blue, gold, navy, and white",
        "logo": "official Los Angeles Chargers lightning-bolt logo",
        "helmet": "powder-blue Chargers helmet with the gold bolt",
        "figures": "Sid Gillman, Don Coryell, and Dan Fouts",
        "players": "Lance Alworth, Kellen Winslow, Junior Seau, LaDainian Tomlinson, Justin Herbert",
        "trophies": "1963 AFL championship trophy and the Super Bowl XXIX AFC trophy",
        "motto": "BOLT UP. HONOR POWDER BLUE. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Chargers lightning bolts, never Dallas stars",
    },
    "giants": {
        "file_title": "New_York_Giants",
        "display": "The New York Giants",
        "colors_words": "royal blue, red, gray, and white",
        "logo": "official New York Giants lowercase ny logo",
        "helmet": "blue Giants helmet with the lowercase ny",
        "figures": "Wellington Mara, Bill Parcells, and Tom Coughlin",
        "players": "Frank Gifford, Lawrence Taylor, Phil Simms, Michael Strahan, Eli Manning",
        "trophies": "four Super Bowl Lombardi trophies for XXI, XXV, XLII, and XLVI",
        "motto": "ONCE A GIANT. ALWAYS A GIANT. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Giants ny marks, never Dallas stars",
    },
    "commanders": {
        "file_title": "Washington_Commanders",
        "display": "The Washington Commanders",
        "colors_words": "burgundy, gold, and white",
        "logo": "official Washington Commanders W logo",
        "helmet": "burgundy Commanders helmet with the gold W",
        "figures": "George Preston Marshall era archive, Joe Gibbs, and Jayden Daniels as the present face",
        "players": "Sammy Baugh, John Riggins, Joe Theismann, Darrell Green, Art Monk",
        "trophies": "Super Bowl XVII, XXII, and XXVI Lombardi trophies",
        "motto": "HAIL. HONOR BURGUNDY AND GOLD. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Commanders W marks, never Dallas stars",
    },
    "bears": {
        "file_title": "Chicago_Bears",
        "display": "The Chicago Bears",
        "colors_words": "navy blue, burnt orange, and white",
        "logo": "official Chicago Bears wishbone-C logo",
        "helmet": "navy Bears helmet with the orange wishbone C",
        "figures": "George Halas, Mike Ditka, and Walter Payton",
        "players": "Red Grange, Bronko Nagurski, Dick Butkus, Gale Sayers, Walter Payton",
        "trophies": "nine NFL championship trophies including Super Bowl XX",
        "motto": "BEAR DOWN. HONOR PAPA BEAR. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Bears wishbone-C marks, never Dallas stars",
    },
    "lions": {
        "file_title": "Detroit_Lions",
        "display": "The Detroit Lions",
        "colors_words": "Honolulu blue, silver, and white",
        "logo": "official Detroit Lions leaping-lion logo",
        "helmet": "silver Lions helmet with the Honolulu-blue lion",
        "figures": "Bobby Layne, Barry Sanders, and Dan Campbell",
        "players": "Dutch Clark, Bobby Layne, Barry Sanders, Calvin Johnson, Amon-Ra St. Brown",
        "trophies": "1952, 1953, and 1957 NFL championship trophies",
        "motto": "ONE PRIDE. HONOR THANKSGIVING. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Lions leaping-lion marks, never Dallas stars",
    },
    "packers": {
        "file_title": "Green_Bay_Packers",
        "display": "The Green Bay Packers",
        "colors_words": "dark green, gold, and white",
        "logo": "official Green Bay Packers G oval logo",
        "helmet": "yellow Packers helmet with the green G",
        "figures": "Curly Lambeau, Vince Lombardi, and Bart Starr",
        "players": "Don Hutson, Ray Nitschke, Reggie White, Brett Favre, Aaron Rodgers",
        "trophies": "thirteen championship trophies including Super Bowls I, II, XXXI, and XLV",
        "motto": "HONOR LAMBEAU. RESPECT THE TUNDRA. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Packers G marks, never Dallas stars",
    },
    "vikings": {
        "file_title": "Minnesota_Vikings",
        "display": "The Minnesota Vikings",
        "colors_words": "purple, gold, and white",
        "logo": "official Minnesota Vikings profile-Norseman logo",
        "helmet": "purple Vikings helmet with the Norseman horns",
        "figures": "Bud Grant, Fran Tarkenton, and Alan Page",
        "players": "Carl Eller, Cris Carter, Randy Moss, Adrian Peterson, Justin Jefferson",
        "trophies": "1969 NFL championship trophy and four Super Bowl conference trophies",
        "motto": "SKOL. HONOR THE NORTH. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Vikings Norseman marks, never Dallas stars",
    },
    "falcons": {
        "file_title": "Atlanta_Falcons",
        "display": "The Atlanta Falcons",
        "colors_words": "red, black, silver, and white",
        "logo": "official Atlanta Falcons aggressive falcon-F logo",
        "helmet": "black Falcons helmet with the red falcon F",
        "figures": "Arthur Blank, Dan Reeves, and Matt Ryan",
        "players": "Tommy Nobis, Deion Sanders, Michael Vick, Julio Jones, Matt Ryan",
        "trophies": "1998 and 2016 NFC championship trophies",
        "motto": "RISE UP. HONOR THE BIRD. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Falcons F marks, never Dallas stars",
    },
    "panthers": {
        "file_title": "Carolina_Panthers",
        "display": "The Carolina Panthers",
        "colors_words": "process blue, black, and silver",
        "logo": "official Carolina Panthers snarling-panther logo",
        "helmet": "silver Panthers helmet with the blue-black panther",
        "figures": "Jerry Richardson, Sam Mills, and Cam Newton",
        "players": "Muhsin Muhammad, Julius Peppers, Steve Smith, Luke Kuechly, Cam Newton",
        "trophies": "2003 and 2015 NFC championship trophies",
        "motto": "KEEP POUNDING. HONOR THE CAT. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Panthers marks, never Dallas stars",
    },
    "saints": {
        "file_title": "New_Orleans_Saints",
        "display": "The New Orleans Saints",
        "colors_words": "old gold, black, and white",
        "logo": "official New Orleans Saints fleur-de-lis logo",
        "helmet": "gold Saints helmet with the black fleur-de-lis",
        "figures": "Archie Manning, Sean Payton, and Drew Brees",
        "players": "Tom Dempsey, Rickey Jackson, Drew Brees, Alvin Kamara, Michael Thomas",
        "trophies": "the Super Bowl XLIV Lombardi Trophy",
        "motto": "WHO DAT. HONOR THE FLEUR-DE-LIS. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Saints fleurs-de-lis, never Dallas stars",
    },
    "buccaneers": {
        "file_title": "Tampa_Bay_Buccaneers",
        "display": "The Tampa Bay Buccaneers",
        "colors_words": "buccaneer red, pewter, orange, and black",
        "logo": "official Tampa Bay Buccaneers skull-and-swords flag logo",
        "helmet": "pewter Buccaneers helmet with the red skull flag",
        "figures": "Lee Roy Selmon, Jon Gruden, and Tom Brady in a Buccaneers jacket",
        "players": "Warren Sapp, Derrick Brooks, John Lynch, Mike Evans, Tom Brady",
        "trophies": "Super Bowl XXXVII and Super Bowl LV Lombardi trophies",
        "motto": "FIRE THE CANNONS. HONOR THE SHIP. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Buccaneers skull-flag marks, never Dallas stars",
    },
    "cardinals": {
        "file_title": "Arizona_Cardinals",
        "display": "The Arizona Cardinals",
        "colors_words": "cardinal red, black, yellow, and white",
        "logo": "official Arizona Cardinals cardinal-head logo",
        "helmet": "white Cardinals helmet with the red cardinal head",
        "figures": "Charles Bidwill, Kurt Warner, and Larry Fitzgerald",
        "players": "Ottis Anderson, Anquan Boldin, Larry Fitzgerald, Patrick Peterson, Kyler Murray",
        "trophies": "the 1947 NFL championship trophy and the Super Bowl XLIII NFC trophy",
        "motto": "BIRD GANG. HONOR THE OLDEST BIRD. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Cardinals bird-head marks, never Dallas stars",
    },
    "49ers": {
        "file_title": "San_Francisco_49ers",
        "display": "The San Francisco 49ers",
        "colors_words": "scarlet, gold, and white",
        "logo": "official San Francisco 49ers interlocking SF logo",
        "helmet": "gold 49ers helmet with the scarlet SF",
        "figures": "Bill Walsh, Eddie DeBartolo Jr., and Joe Montana",
        "players": "Jerry Rice, Ronnie Lott, Steve Young, Patrick Willis, Brock Purdy",
        "trophies": "five Lombardi trophies for Super Bowls XVI, XIX, XXIII, XXIV, and XXIX",
        "motto": "FAITHFUL TO THE BAY. HONOR THE GOLD RUSH. COMPLETE THE LEGACY.",
        "border_motif": "repeating official 49ers SF marks, never Dallas stars",
    },
    "rams": {
        "file_title": "Los_Angeles_Rams",
        "display": "The Los Angeles Rams",
        "colors_words": "royal blue, sol yellow, and white",
        "logo": "official Los Angeles Rams leaping ram-head and horn curl",
        "helmet": "blue-and-yellow Rams horned helmet",
        "figures": "Georgia Frontiere, Dick Vermeil, and Sean McVay",
        "players": "Merlin Olsen, Deacon Jones, Eric Dickerson, Aaron Donald, Matthew Stafford",
        "trophies": "Super Bowl XXXIV and Super Bowl LVI Lombardi trophies",
        "motto": "THE HORNS ARE ALWAYS HOME. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Rams horn curls, never Dallas stars",
    },
    "seahawks": {
        "file_title": "Seattle_Seahawks",
        "display": "The Seattle Seahawks",
        "colors_words": "college navy, action green, wolf grey, and white",
        "logo": "official Seattle Seahawks profile seahawk logo",
        "helmet": "navy Seahawks helmet with the blue-green seahawk",
        "figures": "Paul Allen, Pete Carroll, and Mike Holmgren",
        "players": "Steve Largent, Cortez Kennedy, Walter Jones, Marshawn Lynch, Russell Wilson",
        "trophies": "the Super Bowl XLVIII Lombardi Trophy",
        "motto": "GO HAWKS. HONOR THE 12S. COMPLETE THE LEGACY.",
        "border_motif": "repeating official Seahawks bird marks, never Dallas stars",
    },
}
