"""Long extras for remaining AFC teams (index-aligned with build_guidebooks stops)."""

AFC = {
    "patriots": [
        "An AFL club named for a revolution, playing in borrowed Boston parks before anyone believed New England could own a dynasty. The cradle is a nickname looking for a home. The red, white, and blue came first; the rings came much later.",
        "Fenway and Nickerson were not cathedrals. They were favors. The map marks them because the franchise learned to be serious in other people's buildings. Home, at first, was a schedule, not a stadium.",
        "Babe Parilli's arm and Gino Cappelletti's all-purpose Sundays were the first AFL stars the region could point to. The grove is competence before glamour. They made the Patriots a real club, not a logo on a program.",
        "The first almost. An AFL title game that taught New England how close could still feel like nothing. The vale is the original heartbreak, older than Foxborough.",
        "A no-frills bowl in the wind, with metal stands and weather that treated visitors as underdressed. Foxboro Stadium was the swamp where the later dynasty learned its manners. Nothing about it was pretty except the winning that eventually happened there.",
        "Good teams, bad breaks, and a region that had not yet learned to expect January. The 1970s ridge is almost-football. The map keeps it so the later trophies do not look inevitable.",
        "The Bears' lesson, delivered in a Super Bowl the Patriots were not ready to survive. Loss Shore is the last pre-dynasty humiliation, a reminder that New England once lost in ways that felt ordinary.",
        "The arm that later handed the job to a sixth-rounder. Bledsoe made the Patriots a quarterback franchise again and then, on one injured Sunday, opened the door history walked through. The harbor is the last analog hero before 12.",
        "Parcells made them a playoff team again with the same glare that had already won in New York. The return citadel is coaching as a reset: tough, loud, and suddenly respectable.",
        "The owner of the dynasty years bought a struggling club and then refused to treat it like a toy. Kraft's crown is the business half of six banners. The map marks ownership because this dynasty had a landlord who stayed.",
        "A sixth-round kid becoming 12, first as an emergency and then as a law. Shea Day is the draft-room accident that remade the sport. The map paints a young quarterback walking onto a field that did not yet know his name.",
        "Snow, Oakland, and a rule that built a dynasty. The Tuck Rule night is the hinge: one incomplete that became a fumble that became a kick that became a decade. New England still argues the rule. The map just marks the weather.",
        "The first Lombardi, an upset that made Belichick and Brady a single civic sentence. Super Bowl XXXVI is the night the region learned it could be cruel in January and blessed in February.",
        "Two controversies the map marks without celebrating, because the dynasty's shadow is part of the record. The canyons are not trophies. They are the cost of being watched that hard.",
        "The perfect regular season, 18-0, a mountain that still has no Super Bowl companion. The plains are excellence that did not finish. New England remembers the wins and the last night in Arizona.",
        "Butler's intercept on the goal line, the play that turned a second dynasty into scripture. Super Bowl XLIX is one yard and one throw that Seattle still sees with its eyes closed.",
        "The greatest comeback, 28-3 erased in overtime, a Super Bowl that became a proverb. Climb is the right word. The map paints a mountain that should have been too steep.",
        "The last Brady-Belichick trophy, a defensive grind that closed the book without a farewell speech. Super Bowl LIII is the quiet last crown. The lighthouse was still on.",
        "A ship leaving a New England coast, number 12 going south, a partnership ending like weather. Departure Horizon is not bitterness on this map. It is a tide that went out.",
        "The lighthouse of the dynasty, a stadium that still looks like it expects January. Gillette is the present house of a past empire, and the map will not pretend otherwise.",
    ],
    "ravens": [
        "Baltimore got football back and named it for Poe, a dark bird for a city that had been robbed of its last one. The 1996 harbor is relief and invention. Purple was a new color for an old football town.",
        "Ozzie drafted the spine of two champions: Ogden, Lewis, Reed, and later the pieces of a second title. The architect citadel is a personnel department as a civic institution. Ravens football still walks through his tree.",
        "Lewis was the emotional and physical center of Raven Nation, a middle linebacker who made pregame a sacrament and Sundays a hunt. The volcano is still the loudest landmark on this map.",
        "Reed intercepted the league's imagination, a safety who played like he could hear the snap in another zip code. Safety Island is range, ball skills, and a purple secondary that became folklore.",
        "Ogden was a dancing mountain at left tackle, the first brick Ozzie laid and the one that never moved. The fortress is the blind side of the first champion.",
        "A defense so good it felt like a purple wall, Super Bowl XXXV remains the cleanest Ravens title. First Crown is Trent Dilfer managing a storm and a city remembering how parades work.",
        "Sharpe gave the first title team a tight end who talked and blocked, a veteran voice in a young locker room. The grove is the last missing piece of that defense-first champion.",
        "The downtown bowl that turns purple on Sunday, M&T is the house the city walks to. The coliseum sits on the Inner Harbor's shoulder. Home games here are a civic uniform.",
        "John Harbaugh built a second champion on competition, brotherhood, and a refusal to make the roster comfortable. The citadel is a coaching culture that still sounds like training camp in January.",
        "Flacco, Jacoby Jones, and a Super Bowl that lost its lights. Super Bowl XLVII is chaos that ended in a second Lombardi. Blackout Peak is the night New Orleans went dark and Baltimore stayed loud.",
        "One January, elite was not a joke. Flacco's playoff run to Super Bowl XLVII is a harbor the map keeps even when regular seasons were quieter. Hot quarterbacks become landmarks here.",
        "Sizzle hunted quarterbacks for a generation, a pass rusher who aged into a civic uncle and a sack artist. The canyon is longevity as violence.",
        "Yanda was the quiet best guard in football, a technician who made the interior look solved. Trench Plains are the uncelebrated half of two title cultures.",
        "Lamar made the Ravens' offense a new kind of weather, a dual-threat that forced the league to redraw its defensive maps. The river is still moving. MVP seasons live here.",
        "Henry brought Oilers thunder into purple, a present-tense power back who made November look prehistoric. Power Road is the newest rushing landmark on an old defensive map.",
        "The city wears the bird before kickoff, a Friday that turns downtown into a procession. Purple Friday is not marketing. It is the civic corridor this franchise asked for and received.",
        "Domino Sugars, Fort McHenry, and the harbor sit on the map because Baltimore is not a generic East Coast backdrop. It is a port that already knew birds and banners.",
        "The band is part of the franchise's civic sound, a marching tradition that makes Sundays feel like a city event instead of a broadcast. The grove is brass and purple.",
        "Poe's city and a football team sharing one dark bird, a literary joke that became a religion. Nevermore Woods is the gothic half of the brand, kept with a straight face.",
        "Two crowns, and a defense that still believes in the house. The purple horizon is the next wall they will ask the city to protect.",
    ],
    "bengals": [
        "Paul Brown built a second Ohio team and striped it orange, an AFL original that carried his name onto the stadium. The cradle is a founder who had already invented modern football once and then did it again.",
        "The founding coach's name is still on the stadium, a civic argument that the past is not a museum. The citadel is Paul Brown as architecture. Cincinnati football still answers to him.",
        "A cookie-cutter bowl on the Ohio that felt like home because the river was right there. Riverfront is the first true Bengals harbor, ugly and beloved.",
        "Anderson was the first great Bengal quarterback, a precise passer who made the 1980s almost-dynasty possible. The signal tower is the original Who Dey arm.",
        "The Shuffle made a Super Bowl run into a dance the country could do in a kitchen. Ickey's grove is joy as a landmark. Cincinnati still knows the steps.",
        "The first Super Bowl ended in San Francisco, a heartbreak that taught Who Dey how close could feel. Vale XVI is the beginning of a pattern the map refuses to romanticize.",
        "Montana's drive broke Cincinnati again, Super Bowl XXIII becoming a campfire the city still sits around. Heartbreak Peak is one last drive that would not die.",
        "Munoz is the standard at left tackle, a Hall of Famer who made the blind side look like a finished science. The fortress is the best Bengal many scouts will name first.",
        "Boomer's arm and mouth filled the 1980s, a left-handed showman who made the stripes loud. The pocket grove is swagger before Burrow made it look modern.",
        "Dillon ran angry through late-1990s Sundays, a power back who treated the Ohio River weather as a personal insult. Power River is violence as a rushing style.",
        "Ocho Cinco made the end zone a stage and forced the league to learn a new number. Receiving Shores is celebration as craft. The map keeps the first downs and the dances.",
        "Palmer's years were talent waiting on January, a quarterback era that promised more than it was allowed to finish. Era Ridge is the almost of the 2000s.",
        "The river palace of Who Dey Nation, Paycor sits on the water like a dare to the rest of Ohio. The coliseum is the present jungle. Stripes look right under those lights.",
        "Burrow turned a 2-14 start into a Super Bowl trip and made a city believe the stripes could travel. Cannon Peak is the present quarterback as folk hero. Joe Cool in orange.",
        "Chase and Burrow from LSU to the NFL felt inevitable, a deep-threat pairing that made every Sunday a vertical problem. Receiving Lightning is the modern Bengals identity.",
        "Higgins is the other half of the modern deep shots, a big-bodied threat who makes the jungle two-sided. The grove is complementary firepower.",
        "Stafford's Rams won a game Cincinnati still replays, Super Bowl LVI sitting on the map as the closest modern crown. Almost Crown is not a consolation. It is a scar that still itches.",
        "Flying pigs and the Roebling Bridge mark the city because Who Dey is a place, not a chant imported from elsewhere. The jungle corridor is Cincinnati itself.",
        "The riverfront skyline is painted into the land, a specific bend of the Ohio. Civic Shores refuse a generic Midwest backdrop.",
        "Who Dey is not a question anymore. It is a map. The stripe horizon is the next January they intend to finish.",
    ],
    "browns": [
        "Paul Brown invented a modern franchise in postwar Cleveland, complete with playbooks, facemasks, and the idea that coaching was teaching. The 1946 cradle is the NFL learning a new accent. The Dawgs begin as a classroom.",
        "Playbooks, facemasks, and the teaching tree start here. The innovator citadel is a coach so foundational the team still wears his name. Cleveland football is a Paul Brown argument that never ended.",
        "Graham won titles like they were scheduled, a quarterback who made championships look like the next item on a clipboard. The tower is the winningest early chapter in franchise history.",
        "Motley helped reopen the NFL to Black stars and then ran over the men who had kept the door closed. Integration Gates is football history, not a sidebar. The map will not let visitors walk past it.",
        "The greatest Browns back, and still the argument starter whenever someone says greatest ever. Jim Brown's rushing rivers are power, speed, and a glare that treated defenders as temporary. Canton was a formality.",
        "The last title, still the mountain the city climbs, 1964 sits on this map like a peak that has not been re-summited. Championship Peak is pride and unfinished business in the same stone.",
        "The Toe made field goals a Cleveland art, a specialist who became a folk hero before specialists were fashionable. Automatic Toe Ridge is the kicking game as civic craft.",
        "The Mistake by the Lake was never a mistake on Sunday. Municipal Stadium was wind, dirt, and a lakefront that made visitors look unprepared. The harbor is weather as home-field advantage.",
        "Kosar and the Dawgs made the 1980s loud, a quarterback with a local accent and bleachers that named themselves. The grove is the last great analog roar before exile.",
        "Two January wounds that still have names. The Drive and The Fumble are canyons because Cleveland does not need them explained. The map carves them anyway, so outsiders can see the cost.",
        "The move to Baltimore is remembered, not celebrated, a civic theft the map marks in a quiet color. Exile Vale is the year the Dawgs were put in boxes. Cleveland did not forget the trucks.",
        "An expansion club wearing the old colors came home in 1999, a return that was love and rebuilding at once. Return Harbor is the city getting its name back even when the wins were slow.",
        "The lakefront bowl of the modern Dawgs, a stadium that still faces the water like the old one did. The coliseum is orange helmets against gray weather. Home looks like Cleveland on purpose.",
        "Ten straight Pro Bowls, zero drama, all trench. Joe Thomas is the modern standard of professionalism in brown and orange. The fortress is a left tackle who never needed a subplot.",
        "A Heisman first pick who made Cleveland loud again, Baker's era was hope you could hear from the parking lot. Era Ridge is a reminder that noise and banners are not the same landmark.",
        "Garrett is the best pass rusher the Dawgs have ever drafted, a present-tense wrecking ball who made the edge a destination. Present Canyon is the defensive hope the city can actually touch.",
        "Chubb runs north like the lake wind, a power back whose cuts still look like decisions made a yard before contact. Power River is the rushing identity Cleveland recognizes.",
        "The bleacher nation that named itself, the Dawg Pound is not a section. It is a civic invention. The map paints the barking as architecture.",
        "Terminal Tower, the Rock Hall, and the lake sit on the map because this franchise only makes sense beside that water. Civic Shores are industrial beauty, not a postcard.",
        "The next title is the one this city still deserves, and the horizon does not pretend it has arrived. Dawg Legacy is a promise the map is willing to wait for.",
    ],
    "steelers": [
        "The Chief bought a franchise and a city's Sundays, a founding owner who treated Pittsburgh like a calling. The forge is the Rooney name as civic infrastructure. Black and gold start as a family decision.",
        "Decades of almost before the 1970s, mill-town football that lost more than it liked to admit. The neighborhood is the lean years the dynasty later made look inevitable. It was not.",
        "Noll drafted a dynasty and taught it to work, a coach who valued the job more than the speech. The citadel is four Super Bowls built from the same stubborn classroom.",
        "Greene, White, Greenwood, Holmes: a front that made the 1970s look unfair. Steel Curtain Fortress is the defensive half of the first empire. Offenses still study it like weather.",
        "Franco's catch that still looks impossible, a deflected prayer that became the franchise's origin myth in full color. Immaculate Reception Ridge is the play Pittsburgh uses to tell children who they are.",
        "Bradshaw won four and laughed last, a rifle-armed quarterback who survived the jokes and then collected the rings. The tower is swagger that got receipts.",
        "The first of four in six years, Super Bowl IX is the moment the mill town became a national dynasty. First Crown is the lid coming off.",
        "Swann's grace in the air, Super Bowl X as ballet in a violent sport. Repeat Peak is the second title arriving before the city had finished celebrating the first.",
        "A third title in the same decade, Super Bowl XIII proving the dynasty was a machine, not a mood. Three-Peat Path is black and gold as a law of the 1970s.",
        "The close of the first dynasty, Super Bowl XIV in the California sun. Four-Title Horizon is the last of the Noll-Bradshaw peaks, still the standard the mill measures against.",
        "The toughest commercial in football history and a defensive tackle who became a folk saint. Mean Joe's soda shore is popular culture walking onto the map because Pittsburgh claimed it.",
        "Lambert looked like the Steel Curtain felt: gap-toothed, furious, and unavoidable. The ridge is the middle linebacker as a Halloween story that happened to win titles.",
        "A cookie-cutter bowl that became sacred because the three rivers were right there and the towels were already spinning. Three Rivers Harbor is the house of the first empire.",
        "Heinz Field by a new name, same three rivers, same Terrible Towels. The modern coliseum is continuity. Pittsburgh does not need a spaceship to feel like home.",
        "Cowher's jaw won a Super Bowl and a city, a coach who looked like the mill and sounded like the stands. The citadel is the second dynasty's first voice.",
        "Bettis rode home a champion, Super Bowl XL as a bus pulling into Detroit with a city's favorite back finally holding the trophy. Bus-to-Glory Peak is sentiment that got to finish.",
        "Santonio's toes in the grass, Super Bowl XLIII as a catch that still looks like it should have been out of bounds. Holmes Catch Summit is the third modern crown and the prettiest ending.",
        "Big Ben extended plays until they became wins, a quarterback who treated collapsing pockets as extra time. The pocket grove is two Super Bowls and a generation of almost-escapes.",
        "Watt is the present sack king of the mill, a pass rusher who made the edge feel like the 1970s again. Present Canyon is the defensive future wearing the same colors.",
        "Bridges, the Incline, and Terrible Towels sit on the map because Pittsburgh is not a generic tough-town backdrop. It is three rivers and a specific gold. Civic Shores keep the smoke and the light.",
    ],
    "texans": [
        "Houston got football back and branded it with a bull after the Oilers left a hole the city refused to leave empty. The 2002 cradle is a second beginning. Battle red was a new language for an old football town.",
        "A retractable-roof palace built for a new Texas team, NRG is the house that made expansion feel expensive on purpose. The coliseum is still the bull's first true home.",
        "The first pick learned behind a young line, a quarterback chapter that taught the franchise patience the hard way. First Harbor is the cost of being new.",
        "Andre was the first Texans legend, period: a receiver who made a young club look like it had a history. Receiving Rivers is the original Houston star, the one the map names without a qualifier.",
        "The first overall pick who actually rushed the passer, Mario Williams made the edge a Texans position. Pass-Rush Canyon is the first defensive identity that stuck.",
        "Foster made zone-read fashionable in Houston and turned a committee backfield into a national conversation. Zone-Read Grove is innovation wearing battle red.",
        "Watt was a three-time Defensive Player of the Year wrecking crew, a defensive end who made Houston a defensive city. Destroyer Peak is the greatest Texan, and the map does not whisper it.",
        "The first January wins in franchise history, 2011 and 2012, proof that an expansion club could learn playoff weather. Playoff Plains are the first time the bull looked grown.",
        "Nuk caught everything that entered his zip code, a receiver who turned contested balls into personal property. Receiving Shores is the second great Houston wideout tradition.",
        "A stretch of AFC South titles and quarterback weather, the O'Brien years were contention without a Super Bowl shoreline. Era Ridge is the almost of the 2010s.",
        "A hard chapter the map marks without celebrating, because some valleys are part of the honest walk. Storm Vale is not a highlight. It is a boundary stone.",
        "Back-to-back division banners in battle red, 2018 and 2019, a twin-peak reminder that the bull could own its division. The peaks are real even if the next Sunday was not.",
        "A former Texans linebacker came home to coach, DeMeco Ryans carrying the locker room's memory into the headset. Coach Citadel is continuity as a plan.",
        "Stroud looked like a veteran as a rookie, a present cannon who made Houston's future feel early. Present Harbor is the quarterback the city had been drafting toward.",
        "Collins became the present deep threat, a big receiver who made the new offense look finished. Receiving Grove is the latest Houston tradition wearing a new number.",
        "The new edge of the bull, Will Anderson Jr. hunting from the same side of the formation Watt once ruined. Pass-Rush Canyon is a second generation, not a tribute act.",
        "A young team that refused to play like an expansion memory, the 2023 climb was January as a personality test. The map marks it as the modern bull waking up.",
        "Skyline, Space Center, and the ship channel sit on the map because Houston is a port, a space city, and a football town at once. Civic Shores keep the humidity and the glass.",
        "The city wears red before kickoff, a Friday that turns Houston into a warning. Battle Red Corridor is civic color as a weekly habit.",
        "A young franchise still writing its first crown, the horizon is unfinished on purpose. The bull is still hungry, and the map leaves room.",
    ],
}
