"""Long extras for AFC South/West remaining teams."""

AFC2 = {
    "colts": [
        "The Colts began in Baltimore with a horseshoe on the helmet, a 1953 birth that still belongs on an Indianapolis map because the name traveled with the colors. The cradle is the original blue. Visitors start here so the later dome does not erase the first city.",
        "Unitas invented the two-minute drill as a way of life, a crew-cut quarterback who made late-game football look like a moral. The signal tower is the horseshoe's first saint. Every later audible still owes him rent.",
        "Berry ran routes like they were drafted on paper, a precise receiver who turned Unitas's throws into geometry. Receiving Rivers is the original Colts passing play, run until it became a Hall of Fame.",
        "A messy, famous first Super Bowl win, Super Bowl V is the franchise's first Lombardi and a game nobody calls pretty. First Crown still counts. The horseshoe learned what a title felt like in the Super Bowl era.",
        "The old Baltimore bowl of blue, Memorial Stadium was brick, noise, and a city that thought the Colts were permanent. The harbor is memory the later move cannot delete.",
        "Mayflower vans and a new city, still a sore memory in one place and a founding myth in another. Midnight Move Crossroads is marked without a celebration. The map tells both cities the truth.",
        "The Hoosier Dome made the Colts a Midwest team, an indoor beginning that taught Indianapolis how to be an NFL town. Arrival Plains are the first Sundays under a roof that was not Baltimore's.",
        "The modern blue palace downtown, Lucas Oil is the house Peyton built a dynasty inside. The coliseum is still the horseshoe's present cathedral.",
        "Manning turned the audible into theater, a quarterback who made pre-snap noise famous and January a local habit. Playbook Peak is the greatest Colt of the Indianapolis era, and the map does not hedge.",
        "The greatest receiving pair in horseshoe history, Harrison and Wayne stretched every defense until the offense looked unfair. Twin Groves are two Hall-level wideouts sharing one blue sky.",
        "Edge was the back of the first Indianapolis dynasty, a complete runner who made the Peyton years physical. Power River is the ground game that kept the audibles honest.",
        "Rain in Miami, a blue trophy going home, Super Bowl XLI is the first title that belongs only to Indianapolis. First Indy Crown is Dungy, Manning, and a city that had waited since the vans.",
        "Brees and the Saints ended the three-peat dream, Super Bowl XLIV sitting on the map as the almost after the parade. Heartbreak Vale is the dynasty's last unfinished Sunday.",
        "Luck's arm and early retirement still sting, a generational quarterback who left before the map was done with him. The harbor is talent and what-if in the same water.",
        "The greatest pass-rush pair the shoe has known, Freeney and Mathis made the edge a two-man wrecking crew. Sack Canyon is the defensive half of the Manning years.",
        "Taylor is the modern power back, a present-tense rusher who made the horseshoe look physical again. Present River is the ground game the current map still trusts.",
        "The next horseshoe passer is still being drawn, a harbor that changes names and keeps the same blue pressure. Present Quarterback Harbor is unfinished on purpose.",
        "Monument Circle, the Speedway, and the canal sit on the map because Indianapolis is a specific Midwest capital, not a generic dome city. Civic Shores keep the brick and the race.",
        "A lucky shape that became a city's mark, the horseshoe is the logo that survived a midnight move and a dynasty. Memorial Grove is the symbol as a civic inheritance.",
        "From Unitas to Manning, the shoe still fits. Bleed Blue Horizon is the next audible the city is waiting to hear.",
    ],
    "jaguars": [
        "Wayne Weaver's expansion club arrived in teal, a 1995 invention that gave Jacksonville a Sunday it did not have to borrow. The cradle is a new color for a river city. Duuuval starts as a county and becomes a cry.",
        "Coughlin made a new team old-school fast, a founding coach who treated expansion like an insult. The citadel is discipline as a shortcut. The Jaguars were in title games before they had a history.",
        "The river bowl that learned to roar Duuuval, EverBank is a stadium that keeps changing names and keeping the same water. The harbor is teal under a Florida sky that still feels like a playoff climate.",
        "Brunell's left arm was the first Jaguar identity, a quarterback who made the expansion years look finished. The signal tower is the original teal passer, still the one old fans name first.",
        "Jimmy Smith and Keenan McCardell stretched every defense, a twin-receiver attack that made the late 1990s Jaguars a matchup problem. Twin Rivers are the first great Jaguar skill pairing.",
        "Taylor was a Hall-level back who never got the bust, a rusher Jacksonville still argues for. Power Road is the franchise's running identity before the wilderness years.",
        "Two AFC Championship games in the first four years, an expansion miracle the league still studies. Twin Vales are how close teal came before it learned how long a rebuild can last.",
        "The first Jaguar in Canton, Boselli is the trench standard the franchise measures against. Tackle Fortress is the left side of those early almost-dynasty teams.",
        "The closest the teal has come to a Super Bowl, 1999 remains the mountain. AFC Championship Peak is the door that did not open, and the map will not relabel it as anything gentler.",
        "A long stretch of almost and rebuild, the 2000s marsh is the wilderness the early success made look surprising. The map marks it so the later climbs have a valley to rise from.",
        "MJD's compact violence led the league in rushing, a back who made a small frame look like a problem. Lightning River is the best Jaguar rushing season of the middle years.",
        "A wild-card run that felt like a second founding, Bortles' playoff grove is the 2017 reminder that Duuuval could still get loud. The map keeps the January that interrupted the wilderness.",
        "A short, loud coaching chapter, Urban Meyer's vale is marked without decorating. Some landmarks are warnings. This is one.",
        "The first overall pick who still owns the future, Lawrence is the present harbor the franchise drafted the whole map toward. The river is waiting on his January.",
        "Etienne is the present complementary back, a speed-and-vision rusher who makes the teal offense two-sided. Power Grove is the current ground game.",
        "Josh Allen and Travon Walker hunt from the edges, a pass-rush canyon that is the modern Jaguar defensive idea. The map paints the pocket collapsing in teal and gold.",
        "A January reminder that Duuuval still believes, the 2022 climb was a wild-card night that felt like weather changing. Playoff Climb is the newest almost that still has a pulse.",
        "The St. Johns, bridges, and beaches sit on the map because Jacksonville is a river city with a coast, not a generic Florida backdrop. Civic Shores keep the water.",
        "A county name turned into a battle cry, Duuuval is the civic corridor this franchise asked the city to shout. The map letters it large on purpose.",
        "The jaguar is still young, and still hungry. Teal Legacy Horizon is the first crown this city has not yet hung, and the map leaves the nail in the wall.",
    ],
    "titans": [
        "Bud Adams' AFL club was Houston's first love, powder-blue Oilers football that still lives on a Tennessee map because the story did not start in Nashville. The 1960 cradle is Luv Ya Blue before the name changed.",
        "Luv Ya Blue was a city in powder blue, Bum Phillips walking the sideline like a sheriff and Houston answering like a choir. The citadel is the Oilers at their most beloved.",
        "Campbell ran through people, not around them, a rushing myth whose thighs still have their own folklore. Power River is the Oilers' greatest player and the most violent landmark on this map.",
        "Moon made the run-and-shoot a highlight film, a quarterback who turned Houston into a passing circus the league could not ignore. The tower is the Oilers' last great offensive weather.",
        "The Eighth Wonder learned football noise, the Astrodome as a space-age bowl that held Luv Ya Blue like a secret. The harbor is indoor thunder in powder blue.",
        "A new state, a temporary stadium, a new name coming. 1997 Tennessee Arrival Plains are the awkward middle: Oilers colors in a different humidity. The map does not skip the move.",
        "Wycheck to Dyson, one lateral, a civic miracle. Music City Miracle Peak is the play that made Tennessee feel like a football capital overnight. The map paints the sideline as a river.",
        "Kevin Dyson a yard short of overtime, Super Bowl XXXIV as the cruelest almost in franchise history. One-Yard Vale is a reach that still has a name. Titans fans do not need the film.",
        "George was the bruising face of the first Titans teams, a back who made the new name look physical. Power Grove is the ground game of the Music City years.",
        "McNair's toughness still defines the franchise, a quarterback who played hurt and made January look personal. The signal tower is the Titans' first true civic saint.",
        "Matthews played forever and blocked everyone, an Oilers-to-Titans trench career that became a Hall of Fame. Trench Fortress is the line as a family business.",
        "The river palace across from downtown Nashville, Nissan Stadium is the present coliseum with the Batman building in the background. The map keeps the Cumberland in the frame.",
        "Henry made 2,000-yard seasons look prehistoric, a king who turned the Titans into a rushing folk tale again. King Henry Road is the greatest modern Titan and a stiff-arm that became geography.",
        "Brown's Tennessee years were a deep-threat clinic, a receiver who made the Titans look explosive before he left. The grove is the passing complement to King Henry's river.",
        "Vrabel's teams played angry and close, a coach who made the Titans a January problem. Coach Citadel is culture as a defensive look.",
        "A wild-card run that reached the door of the Super Bowl, 2019 is the closest modern climb. AFC Title Climb is the night New England looked beatable and Tennessee almost finished the sentence.",
        "The next Titan passer is still being painted, a harbor that changes names after McNair and never quite settles. Present Quarterback Harbor is unfinished weather.",
        "The Batman building, guitars, and the Cumberland sit on the map because Nashville is a music city that learned football, not the other way around. Civic Shores keep the neon and the river.",
        "The sword-and-flame mark of the Titans era, the flaming T is the logo that replaced the oil derrick and then had to earn it. Memorial Grove is the new seal on old history.",
        "From Oilers blue to Titan navy, one long story. Titan Legacy Horizon is the next yard they still owe themselves.",
    ],
    "broncos": [
        "The Broncos began in ugly brown and mustard and survived, an AFL original that had to earn orange. The 1960 cradle is stubbornness before the horse looked proud. Denver stayed anyway.",
        "Thin air and a bowl that stole opponents' legs, Mile High is the franchise's first true weapon. The harbor is altitude as geography. Visitors still feel it in the fourth quarter.",
        "The 1970s defense that named a color, Orange Crush made Denver mean and fashionable at once. The fortress is the first time the Broncos felt like a national idea.",
        "The Franchise before Elway had a name, Floyd Little kept the team relevant when the wins were thin. Power River is loyalty as a rushing style. Denver still calls him that on purpose.",
        "Elway's arm and that helicopter spin are civic property, a quarterback who made losing Super Bowls look like unfinished business and then finished it. Helicopter Peak is the greatest Bronco, period.",
        "98 yards in Cleveland, still the greatest two-minute story, The Drive is a canyon because the whole sport still uses it as a proverb. The map paints a frozen sideline and a quarterback who refused the clock.",
        "Three 1980s Super Bowls that ended the wrong way, a vale Elway had to walk through before the horse finally climbed. Heartbreak Vale is the cost of becoming inevitable later.",
        "Elway finally got the horse over the mountain, Super Bowl XXXII as the civic exhale of a generation. First Crown is Terrell Davis and a quarterback who had waited too long to smile like that.",
        "Back-to-back titles to close the Elway book, Super Bowl XXXIII is the encore that made the ending look designed. Repeat Peak is the last throw of a civic career.",
        "TD was the MVP engine of the first crown, a back who made the 1997 offense look unsolvable. Super Bowl River is the rushing half of the first Lombardi.",
        "Sharpe talked as well as he blocked and caught, a tight end who made the dynasty loud between snaps. Tight End Grove is the verbal half of those late-1990s titles.",
        "Champ made a sideline into a closed country, a corner who turned shutdown coverage into a Denver landmark. Shutdown Island is the defensive pride of the 2000s.",
        "Manning's last great years were painted orange, a sunset quarterback who borrowed Denver's air and left a record book on fire. Sunset Tower is the 2013 offense as weather.",
        "Miller wrecked Cam Newton and won the last title, Super Bowl 50 as a defensive coronation. Von Miller Crown is the third Lombardi and the newest mountain.",
        "Mile High by a new name, same thin air, Empower Field is continuity wearing a sponsor. The coliseum is still the altitude. The horse still runs there.",
        "A short, expensive chapter, Russell Wilson's ridge is marked without decorating. Some harbors are brief. The map still tells the truth.",
        "The present quarterback of the orange, Bo Nix is the newest hand on a proud passing and running tradition. Present Harbor is unfinished and high above sea level.",
        "Gold-dome Capitol, the Rockies, Union Station: Denver is a specific western light, not a generic mountain sticker. Civic Shores keep the snowline and the brick.",
        "The charging horse is the city's other mountain, a logo that outlived the ugly uniforms and became a civic animal. Memorial Grove is the horse-head as inheritance.",
        "Three crowns, and air that still favors the home team. Orange Crush Horizon is the next ride up the same thin-air road.",
    ],
    "chiefs": [
        "An AFL club that started in Texas, the Dallas Texans are the first name on a Kansas City map because the kingdom moved. The cradle is Lamar Hunt inventing a league and then inventing a city for it.",
        "1963, a new city, a new name. Kansas City Arrival Harbor is the day the arrowhead found the Missouri. The franchise became civic the moment it unpacked.",
        "Stram's stack defense and a first Super Bowl, Super Bowl IV as the AFL's last argument and the Chiefs' first Lombardi. The citadel is the original kingdom, red and gold and sure.",
        "Dawson was the original Chiefs quarterback saint, a passer who made the AFL look finished and then won the last Super Bowl of that war. The signal tower is still the first 16 the city loved.",
        "Two Hall of Famers in the middle, Bell and Lanier made the 1960s defense a wall with opinions. Linebacker Ridge is the original red defensiveness.",
        "The loudest regular-season crater in football, Arrowhead is a sea of red that treats visiting offenses as trespassers. The stadium is not a backdrop. It is the kingdom's mouth.",
        "Thomas hunted quarterbacks like it was personal, a pass rusher whose sack record still looks angry. Sack Plains are the 1990s Chiefs at their most violent and beloved.",
        "A late-career 16 in red, Joe Montana's Kansas City grove is a borrowed legend that still counts as local weather. The map keeps the January he almost finished.",
        "Holmes' peak years were unstoppable, a back who made the early 2000s Chiefs look like a scoring machine. The river is the last great analog rushing peak before the Mahomes weather.",
        "Gonzalez made the position a scoring threat, a tight end who turned the middle of the field into a Chiefs possession. Tight End Terrace is the ancestor of Kelce's harbor.",
        "Reid built the modern kingdom, a playbook architect who made Kansas City a destination instead of a stop. Playbook Citadel is the coaching half of the present dynasty.",
        "Mahomes throws from angles that should not work, a quarterback who made no-look and off-platform look like a regional dialect. Moonball Peak is the present tense of the whole map.",
        "Kelce is the greatest receiving tight end, a harbor who turned third downs into theater and January into a partnership. Tight End Harbor is the other half of the moonball.",
        "The first title of the Mahomes era, Super Bowl LIV ended a fifty-year wait and made the kingdom modern. First Modern Crown is the parade the city had been practicing in its head.",
        "Brady's Buccaneers ended the repeat, Super Bowl LV sitting on the map as the rare January that got away. Heartbreak Vale is a reminder the dynasty can bleed.",
        "A second modern crown, Super Bowl LVII as proof the first was a beginning. Repeat Summit is red and gold climbing again.",
        "A third in five years, Super Bowl LVIII made the modern Chiefs look like a weather system. Three-Peat Path is the newest mountain range on this map.",
        "A rare January that ended early, Super Bowl LIX is marked as an upset vale because dynasties need honest valleys. The map does not skip the loss.",
        "Jones is the interior wrecking ball, a defensive tackle who made the present championships two-sided. Present Fortress is the trench under the moonballs.",
        "Fountains, BBQ smoke, Union Station: Kansas City is a specific river town, not a generic red backdrop. Civic Shores keep the smoke and the stone.",
    ],
    "raiders": [
        "A last-minute AFL club that became a religion, Oakland 1960 is the birth of silver and black as a personality. The cradle is a franchise that arrived late and then acted like it had invented toughness.",
        "Al made the shield a way of life, Commitment to Excellence as a law instead of a slogan. The citadel is an owner who treated the logo like scripture. The nation still speaks in his cadence.",
        "Madden's Raiders won ugly, loud, and often, a coach who looked like the stands and won a Super Bowl anyway. The grove is joy as a blocking scheme.",
        "The Snake threw ducks that won titles, a left-handed quarterback who made chaos look designed. Snake Pocket is the 1970s offense as a bar story that happened to be true.",
        "Glue fingers and a Super Bowl MVP, Biletnikoff made the receiving game look like a contact sport with better hands. Receiving Rivers is the original Raider skill player as folk hero.",
        "The secondary that made receiving a contact sport, Tatum and Hayes turned the middle of the field into a warning. Secondary Fortress is the dark half of the first dynasty, marked without a sermon.",
        "The first silver-and-black Lombardi, Super Bowl XI is the night the outlaw brand got a trophy to match the attitude. First Crown is Madden, the Snake, and a nation that felt seen.",
        "Plunkett and the wild-card champions, Super Bowl XV as the second peak and a quarterback resurrection. Second Peak is proof the shield could win from the bottom of a bracket.",
        "Marcus Allen's long run in Tampa, Super Bowl XVIII as the third horizon and the prettiest Raider highlight of the first empire. Third Horizon is the last of the Al-and-Madden mountains.",
        "Defense and a back who made January look easy, Howie Long and Marcus Allen are twin ridges of the 1980s. The map keeps the pass rush and the long run in the same weather.",
        "A Hollywood chapter that still splits the nation, the Los Angeles Coliseum years are exile and glamour at once. Exile Harbor is marked because the shield lived there, whether Oakland liked the memory or not.",
        "The shield came home before it left again, Return to Oakland Plains are a reunion that did not become forever. The map tells the truth about how many times this nation has packed.",
        "Tampa Bay ended the last Raiders Super Bowl, Super Bowl XXXVII as the last time silver and black played for the last trophy. Heartbreak Vale is the end of the Gruden-vs-Gruden story.",
        "Two Hall of Famers who carried the 1990s-2000s, Tim Brown and Charles Woodson are the grove that kept the brand proud when the banners stopped. The map names them so the wilderness has saints.",
        "A black palace in the desert, Allegiant is the newest Black Hole, a coliseum that made Las Vegas look like it had always had a shield. The map paints neon against silver.",
        "Crosby is the present pass-rush religion, an edge who plays like the old films. Present Canyon is the newest Raider who looks like the brand promised.",
        "A tight end who arrived like a veteran, Brock Bowers is the present skill grove. The map adds him because the future needed a name that already felt finished.",
        "The Strip, the desert, and a welcome sign on the horizon: Las Vegas is a new civic shore for an old nation. The map does not pretend the city has always been home. It paints the move as weather.",
        "The fans who wear the shield like armor, the Black Hole is a fortress that travels. Fan Fortress is the twelfth defender this franchise invented on purpose.",
        "Just win, baby, is still the only law. Silver and Black Horizon is the next Sunday the nation intends to take personally.",
    ],
    "chargers": [
        "The Chargers began in Los Angeles before San Diego claimed them, a 1960 AFL birth that already knew two cities. The cradle is the bolt looking for a home. Powder blue came soon enough to become the truth.",
        "Balboa Stadium and a city that loved powder blue, San Diego Arrival Harbor is the chapter most old fans still mean when they say Chargers. The map keeps both coasts.",
        "Gillman invented the modern vertical passing game, a coach whose ideas still live in every deep shot. Innovator Citadel is the bolt as an offensive philosophy, not just a logo.",
        "Bambi ran past defensive backs like they were statues, Lance Alworth as the original Chargers deep threat. Receiving Rivers is speed that made the AFL look like the future.",
        "Coryell made the pass the point of the sport, an offense so vertical the league had to rename its math. Air Coryell Pass Plains are the 1970s and 1980s as a highlight film.",
        "Fouts threw the ball until records broke, a cannon who made San Diego a passing city. Cannon Peak is the greatest Charger passer of the analog years, beard and all.",
        "Winslow invented the modern tight end, a receiver in a blocker's body who made third downs a Chargers possession. Tight End Grove is the position's origin myth in powder blue.",
        "Steve Young ended the only Chargers Super Bowl, Super Bowl XXIX as the one time the bolt played for the last trophy. Heartbreak Vale is a 49-26 that still feels personal in San Diego living rooms.",
        "Seau was San Diego's heartbeat in a jersey, a linebacker who made the city feel defended. Linebacker Volcano is the civic saint of the 1990s, marked with the respect the city still uses.",
        "Tomlinson danced into the end zone and into Canton, a back who made the 2000s Chargers look unstoppable and still left without a ring. Lightning River is the greatest Charger many fans will name first.",
        "Rivers talked and threw for a generation, a quarterback who made the huddle a lecture and the numbers a mountain. Signal Tower is the modern bolt's loudest voice, Super Bowl-less and essential.",
        "A basketball player who became a Chargers immortal, Antonio Gates turned the seam into a career. Tight End Harbor is the second coming of Winslow in a different century.",
        "The old San Diego bowl still lives on the map, Qualcomm as memory more than address. Memory Grove is the house L.T. and Rivers made loud.",
        "The bolt went home again in 2017, Return to Los Angeles Harbor as a second beginning that still splits the nation. The map marks the move the way it marks the first one: honestly.",
        "A shared palace with the Rams, SoFi is a spaceship the bolt has to borrow. Shared Coliseum is glamour without a private front door.",
        "Herbert's arm is the present-tense bolt, a cannon who made the Los Angeles chapter look talented from the first snap. Present Cannon Peak is the future the franchise keeps drafting toward.",
        "Mack brought wrecking-ball energy to the edge, a pass rusher who made the bolt look defensive for a stretch. Pass-Rush Canyon is complementary weather.",
        "Coronado, palms, and a distant Hollywood sign: the civic shores are two cities on purpose. The map refuses to pick only one coastline.",
        "The lightning mark that outlived two cities, Bolt Memorial Grove is the logo as the one constant. Powder blue still looks like the truth even when the helmet is a different shade.",
        "The bolt still looks best in powder blue. Powder Blue Horizon is the next January this franchise has been promising since Gillman.",
    ],
}
