"""Long extras for NFC teams (index-aligned with build_guidebooks stops)."""

NFC = {
    "cowboys": [
        "An expansion club that built a culture of excellence from a 1960 empty cupboard, Clint Murchison and Tex Schramm inventing a franchise that acted older than it was. Expansion Frontier Plains are wagons and a future stadium glowing on the horizon.",
        "Twenty-nine seasons and a fedora that became a civic mark, Landry Hat Summit is a coach as geography. The mountain is shaped like the hat because Dallas still sees him that way.",
        "A generation of January football, the twenty-win-streak years are the first time America's Team looked inevitable. The ridge is winning as a habit, not a mood.",
        "A title game so cold it became folklore, the Ice Bowl is a frozen arena Dallas still argues and still honors. The map paints breath in the air and a star that would not get warm.",
        "Lilly, Howley, White, and a nickname that stuck, Doomsday Defense Fortress is the 1970s wall that made Super Bowls possible. Offenses still talk about it in the past tense like weather.",
        "Captain America in a Cowboys jersey, Staubach made the star look heroic on purpose. Captain America Shores are scrambles, comebacks, and a nickname the city did not invent as a joke.",
        "The first Lombardi, Super Bowl VI as the night the expansion project became a champion. Victory Ridge is the first star on the helmet that counted as a crown.",
        "The second, Super Bowl XII as proof the 1970s were a dynasty, not a lucky January. Championship Peak is Doomsday and a quarterback who already knew the way.",
        "The hole in the roof so God could watch, Texas Stadium Star Harbor is the house a generation still means when they say Cowboys. The map keeps the hole. The star needs the sky.",
        "The trade that built the 1990s, Herschel Walker Crossroads is personnel as destiny. Dallas sent a back to Minnesota and received a dynasty in the return mail.",
        "Aikman, Irvin, Emmitt: the Triplets Dynasty Citadel is the 1990s as a three-headed machine. The map paints them together because the city still says the names as one word.",
        "The first of three in four years, Super Bowl XXVII as the lid coming off the second empire. Triumph Plains are a blowout that felt like a beginning.",
        "Repeat. Super Bowl XXVIII is back-to-back as a Dallas expectation. The summit is the second modern crown before the third was even scheduled.",
        "The third crown of the decade, Super Bowl XXX closed the Triplets book with a Larry Brown steal and a city that thought this would never stop. Three-Peat Horizon is the last of that weather.",
        "A nickname that became a brand, America's Team Banner Peaks are marketing and truth tangled together. The map marks the phrase because the league still uses it, whether rivals like the sound or not.",
        "The names the star keeps, Ring of Honor Memorial Grove is the civic cemetery of excellence. Visitors walk it to remember that the star is a roster, not just a shape.",
        "The owner who remade the franchise, Jerry Jones Rebuild Forge is the 1989 purchase as a new founding. The map does not pretend the modern Cowboys have any other landlord.",
        "Jerry World, AT&T Stadium Modern Coliseum is a spaceship with a star on the fifty. The present house is huge on purpose. The map paints the video board like a second sky.",
        "The all-time rushing king, Emmitt Smith Rushing Rivers are 18,355 yards as geography. The map gives him his own water because the record still has his name on it.",
        "The star that still means Dallas, Star on the Helmet Legacy Shores are the last line of the walk. Respect the star is not a caption. It is the law this map was drawn to keep.",
    ],
    "giants": [
        "Tim Mara planted football in a baseball park, the Polo Grounds as a New York idea that happened to be a franchise. The cradle is the NFL learning it needed this city. Big Blue starts as a landlord's bet.",
        "One gate receipt proved the NFL could sell New York, Red Grange Gate is the day the league stopped looking like a Midwest secret. The map marks the turnstiles.",
        "An early banner in black and white, 1927 Championship Field is the first time the Giants looked like a city champion. The map keeps the wool jerseys and the old score.",
        "Basketball shoes on ice, a title saved, the Sneakers Game is frozen ridge folklore the franchise still tells like a family story. The map paints the ice and the improvised traction.",
        "Two-way football as a city craft, Tuffy Leemans and Mel Hein Citadel is the Giants as a trench town. New York football learned its manners here.",
        "Gifford's golden New York team, 1956 Championship Yankee Stadium is glamour in a borrowed cathedral. The map keeps the Yankee facade and the championship weather.",
        "A loss that made the NFL national, the Greatest Game Ever Played is an arena because television found the sport that night. The Giants lost. The league won. The map tells both.",
        "Glamour in a wool Giants jacket, Frank Gifford Halfback Grove is the first modern celebrity Giant. The city still says the name like a broadcast.",
        "Defense as television, Sam Huff Middle Linebacker Ridge is the day the middle of the defense got a camera. The map paints the hit that made linebacker a prime-time job.",
        "Title games that kept slipping, the 1960s Almost-Dynasty Vale is the cost of being good in a hard town. The map marks the near-misses so the later Super Bowls do not look easy.",
        "LT changed the position, Lawrence Taylor Hurricane is a pass rusher who made offenses redesign their weeks. The map paints a storm wearing 56 because that is still how the film looks.",
        "Parcells and Belichick's defense, Bill Parcells Sideline Citadel is the 1980s Giants as a coaching tree and a glare. The map keeps the headset and the two Super Bowl winters.",
        "Simms and the first Super Bowl, Super Bowl XXI Summit is the night Big Blue became a champion in the Super Bowl era. The mountain is a quarterback who got hot at the right time.",
        "Wide right the other way, Super Bowl XXV Crossroads is the Giants winning a game Buffalo still sees in its sleep. The map marks the kick and the defense that made it matter.",
        "A proud franchise in the wilderness, 1990s Wilderness Marsh is the gap between two kinds of Giants excellence. The map does not skip the quiet.",
        "Manning to Tyree, Brady's 18-0 ended, Super Bowl XLII Helmet Catch Peak is the play that still looks impossible in real time. The map paints a helmet as a receiving tool.",
        "Eli did it again, Super Bowl XLVI Repeat Crown is the second giant-killing of a dynasty. The map gives him two mountains because New York does.",
        "Two Super Bowl MVPs, one calm face, Eli Manning Pocket Grove is poise as a personality. The map keeps the last name and the two Februarys.",
        "The families who kept the Giants a Giant thing, Mara-Tisch Ownership Archives are continuity as a civic argument. The map marks the owners because this club still feels inherited.",
        "A shared palace, still Big Blue, MetLife Horizon is the present house with the old ny on the helmet. Once a Giant is the last line, and the map means it.",
    ],
    "commanders": [
        "The franchise began in Boston before it found the capital, a 1932 birth that already knew how to move. The cradle is a club looking for a city worthy of burgundy and gold.",
        "A capital team in burgundy and gold, Washington Arrival Harbor is the day the franchise became a federal Sunday. The map paints the monuments in the distance on purpose.",
        "Slingin' Sammy invented the passing game in wool, a quarterback who made the 1930s and 1940s look modern. Slingin' Tower is the original capital arm, still the first name in the archive.",
        "The loudest horseshoe in the capital, RFK Stadium Roar Coliseum is the house a generation still hears when they close their eyes. The map keeps the RFK rattle.",
        "The Over-the-Hill Gang was built on veterans and belief, George Allen Citadel is coaching as a raid on the waiver wire. The map respects the old legs.",
        "Old legs, Super Bowl VII, one famous almost, Over-the-Hill Gang Ridge is the first Super Bowl trip and the last yard they could not finish. The map marks the pride and the loss.",
        "Gibbs won three Super Bowls with three quarterbacks, a coaching citadel that still looks like a magic trick. Three-Crown Citadel is the standard burgundy still uses.",
        "The Hogs made trench work fashionable, an offensive line that got its own fans and its own nickname. Offensive Line Fortress is the 1980s as a blocking scheme with a cult.",
        "Riggo ran over Miami in Super Bowl XVII, John Riggins Dieselse River as the play that finally brought a Lombardi. The map paints a fourth-and-one that became a parade.",
        "Theismann was the face of the first Gibbs title, a quarterback who made the capital loud and then paid for it on a Monday night the map marks quietly. Signal Grove is the glory and the cost.",
        "The diesel run that finally brought a Lombardi, Super Bowl XVII First Crown is the night burgundy and gold became a Super Bowl color. The city learned the route to a parade.",
        "Doug Williams and an explosion of points, Super Bowl XXII Second Peak is a quarterback making history and a second crown arriving like a storm. The map keeps the first-quarter eruption.",
        "Mark Rypien closed the Gibbs three-title book, Super Bowl XXVI Third Horizon is the last of that weather. The map paints three trophies because the capital still counts that way.",
        "The fastest corner and the longest career, Darrell Green Shutdown Island is speed as a capital landmark. The map gives him a sideline that never aged.",
        "Monk caught everything and said almost nothing, Art Monk Receiving Rivers are quiet excellence as a Hall of Fame. The map names him so the offense of those titles has its hands.",
        "The modern suburban bowl, Northwest Stadium Coliseum is the present house after RFK's roar. The map does not pretend it sounds the same. It still paints the burgundy.",
        "A safety remembered with quiet respect, Sean Taylor Memorial Grove is a landmark the map keeps without a highlight-reel grin. The city still says the name softly.",
        "The present quarterback of burgundy and gold, Jayden Daniels Present Harbor is the newest hand on an old passing tradition. The map leaves him room to write.",
        "The Capitol, monuments, and cherry blossoms sit on the map because this franchise only makes sense in this city. Civic Shores are federal stone and spring pink.",
        "Hail still means this city on Sunday. Burgundy and Gold Horizon is the next banner a capital crowd already knows how to sing.",
    ],
    "bears": [
        "A company team that became Chicago, the Decatur Staleys Founding Grove is the NFL's most stubborn origin story. The map paints a factory town that turned into a bear.",
        "Papa Bear founded the league's most stubborn franchise and then coached it like a family argument. George Halas Citadel is the Bears as the league's oldest living weather system.",
        "A baseball park that hosted Monsters, Wrigley Field Rental Harbor is ivy and leather helmets and a city learning that football could live on the North Side. The map keeps the brick.",
        "Bronko was a two-way myth, Iron Ridge as a man who blocked, ran, and tackled like the sport owed him something. The map paints him larger because the stories already did.",
        "Grange made pro football a ticket in New York and Chicago, the Galloping Ghost Road as the day the NFL learned it could sell. The map marks the barnstorm and the gate.",
        "Luckman ran Halas's T and won titles, a quarterback who made the 1940s Bears look designed. T-Formation Tower is the offensive half of the first great modern Chicago dynasty.",
        "The most famous rout in league history, 73-0 Plains are a championship that still looks like a typo. The map paints the scoreboard because no one believes it until they see it.",
        "Butkus tackled the sport itself, Middle Linebacker Volcano as the meanest Chicago landmark on this walk. The map does not soften him. The city never did.",
        "Sayers was beauty in a Bears jersey, Kansas Comet River as cuts that still look like they happened in water. The map keeps the highlights and the shortness of the career.",
        "Sweetness was the complete Bear, Walter Payton Rushing Rivers as 16,175 yards and a high-step that became civic law. The map gives him the most water because Chicago still does.",
        "Da Coach of the 1985 champions, Mike Ditka Mustache Citadel is a personality that won a Super Bowl and then became a city accent. The map paints the gum and the glare.",
        "The 46 defense and a Super Bowl shuffle, Super Bowl XX Shuffle Peak is the night the Monsters became a music video and a champion. The map keeps the dance and the wreckage.",
        "Columns on the lake, Soldier Field Greek Coliseum is the house that still looks like a ruin and a cathedral at once. The map paints the lakefront wind as a defender.",
        "Urlacher was the 2000s middle linebacker, Linebacker Ridge as the last great Bear who made the middle look famous again. The map names him so Butkus has company.",
        "Hester scored on kicks like it was a video game, Return Lightning Road as the most fun Chicago landmark that still counts as fear. The map paints a kickoff that already looks returned.",
        "Rain in Miami, a second Super Bowl trip, Super Bowl XLI Heartbreak Vale is the night the 2000s Bears ran into a Colts dynasty. The map marks the rain.",
        "Mack's peak years were Bears years, Pass-Rush Canyon as a rented wrecking ball who made Chicago loud again. The map keeps the sacks even if the ending was a trade.",
        "The present quarterback of the navy, Caleb Williams Present Harbor is the newest hand on Papa Bear's oldest problem. The map leaves the harbor open.",
        "The Bean, the L, and the skyline sit on the map because Chicago is a specific windy city, not a generic tough-town sticker. Civic Shores keep the elevated tracks.",
        "Bear Down is still the civic instruction. Monsters of the Midway Horizon is the next shuffle the city intends to dance in February.",
    ],
    "lions": [
        "A small-town NFL club that moved to Detroit, Portsmouth Spartans Founding Grove is the first roar before the city. The map keeps the small-town origin so the later cathedral has a road in.",
        "The Lions arrived and claimed Thanksgiving, Detroit Arrival Harbor 1934 as the day a holiday became a franchise property. The map paints the feast and the first Honolulu blue.",
        "The first great Lions quarterback, Dutch Clark Iron Signal Tower is the leather-helmet passer who made Detroit a real NFL town. The map names him so the later almosts have a founder.",
        "Layne won titles and stayed out late, Championship Citadel as a quarterback who made the 1950s Lions look like a bar story that kept getting rings. The map keeps the smoke and the banners.",
        "Skill and a safety who punted the era, Doak Walker and Yale Lary Grove is two-way excellence as a Detroit craft. The map paints the 1950s as more than one name.",
        "The last championship, still the mountain, 1957 Title Peak is the last time Detroit hung a title and the first thing visitors ask about. The map does not pretend the wait has ended.",
        "Sanders made defenders miss in ways film still cannot explain, Lightning River as the most beautiful Lions landmark and the most unfinished. The map paints a cut that still looks like a rumor.",
        "Sims was the 1980s hope, Rookie Harbor as a Heisman back who made the Silverdome loud before the injuries. The map marks the hope because Detroit remembers how it sounded.",
        "1997, 2,053 yards, then a sudden retirement, Barry's 2k Season Plains are a rushing record that ended like a door slamming. The map keeps both the yards and the silence after.",
        "The annual feast that belongs to Detroit, Thanksgiving Day Arena is a civic monopoly. The map paints the table and the field as the same holiday.",
        "A suburban dome chapter, Pontiac Silverdome Harbor is the house of Barry's prime and a generation of almosts. The map keeps the roof and the roar.",
        "A downtown bowl under glass, Ford Field Downtown Coliseum is the present house, a return to the city's middle. The map paints the glass and the Honolulu blue seats.",
        "Megatron caught the ball in another county, Calvin Johnson Peak as the greatest Lions receiver and a career that ended too soon on purpose. The map names the nickname because the city still does.",
        "Stafford left and won a Super Bowl elsewhere, Exit Horizon as a quarterback Detroit raised and then watched get a ring in another color. The map marks the leaving without a sermon.",
        "Campbell made belief a coaching style, Kneecap Citadel as a man who turned a joke into a culture. The map paints the bite because the city took it seriously.",
        "Hutch is the present edge, Pass-Rush Canyon as the defensive hope that looks like a Lion. The map gives him a lane to hunt in.",
        "Sun God is the present possession king, Amon-Ra St. Brown Receiving Grove as the reliable half of the modern roar. The map keeps the first downs.",
        "The closest modern roar, 2023 NFC Championship Vale is the night Detroit could taste a Super Bowl and then had to put the plate down. The map marks the almost with respect.",
        "Spirit of Detroit, Motown, the Ambassador Bridge: Civic Shores are a specific city that builds things and sings. The map refuses a generic rust-belt sticker.",
        "The next title is the one this city has earned. One Pride Legacy Horizon is the roar the map is still waiting to letter in gold.",
    ],
    "packers": [
        "A packing-company team that became a civic religion, Curly Lambeau Founding Grove is the strangest origin in the league and the most beloved. The map paints a small town that refused to stay small.",
        "The wooden ancestor of Lambeau Field, City Stadium Wooden Bowl is the first Titletown house. The map keeps the planks so the later frozen cathedral has a childhood.",
        "Hutson invented the modern receiver, Receiving Rivers as routes that did not exist until he ran them. The map names him so every later Packers wideout has a source.",
        "Three straight titles in the leather-helmet years, 1929-31 Three-Peat Plains are the first Green Bay empire. The map paints the banners before Lombardi so the later coats have company.",
        "The coat, the hat, and the standard, Vince Lombardi Sideline Citadel is a coach who became a trophy. The map paints the sideline the way the town still sees it: as law.",
        "Starr sneak, 21-17, thirteen below, Ice Bowl Frozen Arena is the coldest cathedral in football. The map paints the breath and the sneak because Titletown still tells it like scripture.",
        "The first Lombardi Trophy, named later for him, Super Bowl I First Crown is the night the packers invented the Super Bowl's first ending. The map keeps the first trophy that later wore his name.",
        "Back-to-back, then a retirement, Super Bowl II Repeat Peak is the close of the Lombardi weather. The map paints two early Super Bowls as a single mountain range.",
        "Starr won when the weather and the moment were worst, Pocket Grove as a quarterback who made January look like a craft. The map names him beside the coat on purpose.",
        "Nitschke was the frozen tundra in a jersey, Middle Linebacker Ridge as the mean half of those titles. The map does not prettify the gap in the teeth.",
        "The only stadium that feels like a town, Lambeau Field Titletown Harbor is the house the public still owns. The map paints the bowl as a civic living room.",
        "White made free agency into a title, Minister of Defense Fortress as the pass rusher who chose Green Bay and then hung a banner. The map keeps the arrival as a turning of the weather.",
        "Favre threw it because he could, Gunslinger Canyon as a quarterback who made Titletown loud and reckless and beloved. The map paints the interceptions and the miracles in the same gold.",
        "Desmond Howard and a return to the mountain, Super Bowl XXXI Summit is the first title of the modern public-ownership era. The map keeps the kick return and the cheese in the stands.",
        "Elway's Broncos ended the repeat, Super Bowl XXXII Heartbreak Vale is the night Titletown learned the 1990s would not be a wire-to-wire empire. The map marks the loss.",
        "Rodgers' Super Bowl XLV was precision as art, Championship Drive as a quarterback who made the pocket look like a finished science. The map paints the last throw of that February.",
        "Woodson made the secondary a second offense, Secondary Grove as a corner who chose Green Bay and then picked the league apart. The map names him so the 2010 defense has a face.",
        "The present quarterback of Titletown, Jordan Love Present Harbor is the newest hand on the oldest quarterback tradition in the league. The map leaves him the frozen keys.",
        "Foam cheese as a civic crown, Cheesehead Civic Monument is joy the town wears on purpose. The map paints the wedge because Titletown invented a hat and then made it holy.",
        "Thirteen crowns, and a town that still owns the team. Titletown Legacy Shores are the last line: honor Lambeau, respect the tundra, keep the stock.",
    ],
}


NFC2 = {
    "vikings": [
        "A northern expansion club in purple and gold, 1961 Expansion Birth Cradle is a cold-weather invention that immediately looked like it had always been here. The map paints the first Norseman against a frozen horizon.",
        "An open-air bowl that invented Viking weather, Metropolitan Stadium Harbor is the house where purple learned to use the cold. The map keeps the frost on the metal.",
        "Page, Eller, Marshall, and Larsen ate offenses, Purple People Eaters Fortress as the 1970s front that made Minnesota famous before it had a Super Bowl. The map paints four names as one wall.",
        "Tarkenton invented the scramble as a personality, Scramble Grove as a quarterback who made the pocket optional. The map paints him running because that is still how the film looks.",
        "Two Hall of Famers who made the purple front famous, Alan Page and Carl Eller Twin Ridges are the pass rush as a civic export. The map names them so the nickname has faces.",
        "The first of four Super Bowl losses, Super Bowl IV Heartbreak Vale is the night the purple learned how a last Sunday can end. The map marks it without a joke.",
        "IV, VIII, IX, XI: four Sundays that still sting, Four-Vale Canyon is the franchise's longest shadow. The map carves four losses as geography because Skol still has to walk around them.",
        "Foreman was the complete back of the 1970s, Power River as the offensive half of those Super Bowl teams. The map keeps the receiving and the running in the same current.",
        "Cris Carter and Randy Moss rewrote receiving in purple, Twin Peaks as two different kinds of impossible. The map paints a high point and a deep point on the same range.",
        "A late-career gunslinger in unexpected colors, Brett Favre Purple Harbor is a borrowed legend who made Minnesota January loud. The map marks the almost and the weather.",
        "AP ran like the ground owed him something, Adrian Peterson All-Day River as a rushing peak that looked prehistoric in a passing league. The map gives him his own water.",
        "The loud inflated roof of the 1980s and 1990s, Metrodome Memory Bowl is indoor thunder the city still hears. The map keeps the fabric sky.",
        "A glassy longship in downtown Minneapolis, U.S. Bank Stadium Glass Coliseum is the present house, a boat that does not need a sea. The map paints the glass and the horns.",
        "Stefon Diggs, last play, into the frozen night, Minneapolis Miracle Catch Peak is the play Minnesota uses to tell children that Skol can still happen. The map paints the sideline as a river.",
        "The Eagles ended the closest modern Super Bowl trip, Super Bowl LII Heartbreak Shore as the newest of the four-vale family. The map marks Philadelphia as weather that once blew the wrong way.",
        "Cousins' years were competence waiting on January, Signal Tower as a quarterback era that won Sundays and then had to explain the last one. The map is honest about the wait.",
        "Jefferson is the present greatest receiver on earth some Sundays, Present Lightning as the newest purple deep threat. The map paints him in gold dust because that is how the highlights look.",
        "A clap and a word that became a nation's sound, Skol Chant Civic Corridor is the civic instrument this franchise invented. The map letters the clap as architecture.",
        "Lakes, skyways, and a longship on the horizon, Twin Cities Civic Shores are a specific northern light. The map refuses a generic frozen sticker.",
        "Skol still means we have not finished. North Legacy Horizon is the fifth Sunday they have not yet been allowed to keep.",
    ],
    "falcons": [
        "Atlanta got an NFL club and a bird that dives, 1966 Expansion Birth Cradle as a city inventing a Sunday. The map paints the first falcon over a skyline that was still growing.",
        "A shared baseball bowl for the first Sundays, Atlanta-Fulton County Stadium Harbor is the original nest. The map keeps the shared turf and the first red helmets.",
        "Mr. Falcon, the first great player, Tommy Nobis Linebacker Ridge is the franchise's first civic saint. The map names him so the later almosts have a founder.",
        "Prime covered the sideline and the highlight reel, Deion Sanders Prime Time Island as a corner who made Atlanta look like television. The map paints the gold chain and the shutdown.",
        "Tuggle tackled everybody for a generation, Jessie Tuggle Grove as the unglamorous half of Falcon pride. The map keeps the tackles because the city still does.",
        "Elway's last ride ended Atlanta's first Super Bowl, Super Bowl XXXIII Heartbreak Vale as the first February that got away. The map marks Denver as the wrong weather.",
        "Vick made quarterback look like a new sport, Dual-Threat River as speed the league had not scheduled for. The map paints a scramble that still looks illegal.",
        "The dance, the banner, the first Super Bowl trip, Dirty Birds 1998 NFC Peak is joy as a civic choreography. The map keeps the Dirty Bird because Atlanta still knows the steps.",
        "The Home Depot owner who stayed through the hard years, Arthur Blank Ownership Crown is continuity as a bet on a city. The map marks the owner because he did not leave.",
        "A falcon-wing roof over downtown, Mercedes-Benz Stadium Coliseum is the present nest, a building that opens like the bird. The map paints the roof mid-flight.",
        "Ryan was the calm face of the 2010s, Matty Ice Tower as a quarterback who made Atlanta competent and then almost eternal. The map names the nickname because the city still does.",
        "Julio caught the ball in another zip code, Receiving Peak as the greatest Falcons wideout and a jump ball that became geography. The map gives him altitude.",
        "The lead that became a campfire ghost story, Super Bowl LI 28-3 Heartbreak Canyon is the landmark visitors already know. The map carves it honestly. Atlanta does not need it explained.",
        "The best Falcons offense of the Super Bowl era, 2016 NFC Title Plains are the regular-season mountain that made 28-3 possible and then unbearable. The map keeps the points.",
        "A tight end drafted like a receiver, Kyle Pitts Present Grove is the newest skill hope. The map leaves him room to become a peak.",
        "The present outside threat, Drake London Receiving Harbor is the newest red shirt in a proud receiving weather. The map paints the present tense.",
        "Peachtree, the phoenix, and the skyline sit on the map because Atlanta is a specific southern capital, not a generic dome city. Civic Shores keep the peach and the glass.",
        "A civic chant painted onto the map, Rise Up Civic Corridor is the instruction this franchise asked the city to shout. The map letters it on the road downtown.",
        "The bird that keeps diving, Falcon Memorial Grove is the logo as a promise. The map keeps the stoop.",
        "The next lead is the one they finish. Rise Up Horizon is the February Atlanta still intends to keep.",
    ],
    "panthers": [
        "A Carolinas club in blue and black, 1995 Expansion Birth Cradle is two states inventing one Sunday. The map paints the first panther over pine and brick.",
        "The uptown bowl of Keep Pounding, Bank of America Stadium Harbor is the house Sam Mills' words still live in. The map keeps the panther statues at the gates.",
        "Capers had them in a conference title game by year two, Founding Citadel as expansion that refused to act new. The map marks the speed of the rise.",
        "An expansion miracle run, 1996 NFC Title Peak is the first time the cat looked grown. The map paints the banner before the franchise had a childhood.",
        "Moose was the first great Panthers receiver, Muhsin Muhammad Grove as the original skill saint. The map names him so the later stars have a source.",
        "Peppers was a deer who hunted quarterbacks, Pass-Rush Canyon as the greatest Panther many scouts will name first. The map paints the edge as a forest.",
        "A last-second kick in Houston, Super Bowl XXXVIII Heartbreak Vale is the first February that got away. The map marks the kick and the silence after.",
        "Kasay's left leg was a franchise constant, Kick Ridge as the specialist who made January a habit. The map keeps the uprights in process blue.",
        "Cam dove into the end zone like it owed him rent, Superman Peak as a quarterback who made the cat a national weather system. The map paints the dunk and the 15-1 air.",
        "Kuechly saw the play before it happened, Linebacker Volcano as the defensive saint of the 2010s. The map names him so Keep Pounding has a middle linebacker.",
        "Von Miller ended the 15-1 season, Super Bowl 50 Heartbreak Shore as the second February that got away. The map marks Denver as the wrong mountain.",
        "The greatest regular season in Panthers history, 2015 15-1 Plains are the mountain that made Super Bowl 50 possible and then unbearable. The map keeps the wins.",
        "Davis played through injuries that would have ended others, Thomas Davis Fortress as toughness the franchise still uses as a definition. The map paints the brace and the play.",
        "The present quarterback of the blue, Bryce Young Present Harbor is the newest hand on a proud dual-threat and pocket tradition. The map leaves the water open.",
        "The next Panthers skill players are still being drawn, Present Receiving Grove as unfinished weather. The map does not invent names it cannot yet defend.",
        "Queen City skyline and a NASCAR horizon, Charlotte Civic Shores are a specific uptown, not a generic south. The map keeps the glass and the speedway light.",
        "Sam Mills' words became the franchise law, Keep Pounding Civic Corridor as a memorial that turned into a weekly instruction. The map letters it on the road to the stadium.",
        "The cat that keeps pounding, Panther Memorial Grove is the logo as a promise. The map keeps the snarl.",
        "Uptown Sundays in process blue, Bank of America Coliseum is the present house named twice on this walk on purpose. Home is the point.",
        "The phrase is the map's last road. Keep Pounding Horizon is the next February the Carolinas still intend to finish.",
    ],
    "saints": [
        "A Saints club for a city that already knew processions, 1967 Expansion Birth Cradle is black and gold arriving in a place that already had parades. The map paints the first fleur-de-lis over the river.",
        "The old bowl before the Dome, Tulane Stadium Harbor is the first nest, a collegiate house that learned Who Dat. The map keeps the old seats.",
        "Archie was the saint of losing years, Pocket Grove as a quarterback who made hope look like a family business. The map names him so the later crown has a father.",
        "A flat-footed kick that rewrote the record, Tom Dempsey 63-Yard Kick Peak is the play the whole league still uses as a proverb. The map paints the kick from the river's edge.",
        "The 1980s linebackers who named a defense, Dome Patrol Linebacker Fortress is the first time the Saints looked like a finished idea. The map paints four names as one wall.",
        "Two Hall-level linebackers of the Patrol, Rickey Jackson and Sam Mills Ridge are the faces of that fortress. The map names them so the nickname has a trench.",
        "The dome that became a civic shelter and a cathedral, Superdome Modern Coliseum is more than a stadium on this map. The city kept itself there. The football came back there.",
        "Good teams that could not finish January, 1980s Almost-Dynasty Vale is the cost of being close in a hard town. The map marks the near-misses.",
        "A coaching chapter Saints fans still joke about, Mike Ditka Heartbreak Marsh is marked without decorating. Some landmarks are warnings wearing a familiar mustache.",
        "A year on the road, a city that came home, Katrina Exile Crossroads is the map's quietest and most important stop. The franchise left. The city did not end. The map tells it that way.",
        "Payton and Brees rebuilt a franchise and a feeling, Sean Payton Rebuild Citadel as coaching that arrived after the flood and made Sundays sound like New Orleans again.",
        "Brees completed everything, including a Super Bowl, Gunslinger Harbor as the greatest Saint and a completion percentage that became civic weather. The map gives him the river.",
        "The only title, and the civic exhale, Super Bowl XLIV First Crown is the night Who Dat became a fact. The map paints Bourbon Street as a victory road.",
        "Bourbon and Canal as a victory road, Who Dat Nation Parade Corridor is the procession this city already knew how to throw. The map keeps the brass.",
        "Kamara is the present Swiss-army back, Present River as the newest Saint who makes the offense look like a trick play that is actually a plan. The map keeps the jet sweeps.",
        "Thomas set a single-season catch record, Receiving Grove as the 2019 mountain of possessions. The map paints the hands.",
        "Davis is the present defensive captain, Present Fortress as the linebacker who kept the Dome sounding mean. The map names him so the patrol has a modern heir.",
        "A no-call that still has a name, 2018 Minneapolis Heartbreak Vale is the newest almost, marked honestly. The map does not relitigate. It records.",
        "The Cathedral, the streetcar, and jazz horns sit on the map because New Orleans is not a generic party sticker. Civic Shores keep the humidity and the hymn.",
        "Who Dat still means we believe. Who Dat Legacy Horizon is the second crown the brass is still practicing for.",
    ],
    "buccaneers": [
        "An expansion club that lost first and later learned to plunder, 1976 Expansion Birth Cradle is a pirate invention that had to earn the ship. The map paints the first creamsicle against a Florida dusk.",
        "Orange jerseys that became beloved in memory, Creamsicle Era Grove is the original look, ugly and then holy. The map keeps the orange because the city still smiles at it.",
        "The first Buccaneer in Canton, Lee Roy Selmon Pass-Rush Canyon is the original pirate who could actually hunt. The map names him so the later defenses have a source.",
        "McKay's dry wit and the first winning teams, John McKay Founding Citadel is a coach who made expansion sound like a joke and then made it a club. The map keeps the one-liners and the wins.",
        "Gruden's defense wrecked the Raiders, Super Bowl XXXVII First Crown as the first time the cannons fired for a Lombardi. The map paints pewter and a wrecked silver-and-black ship.",
        "The heart of the first champion, Warren Sapp and Derrick Brooks Twin Fortresses are the talk and the tackles. The map keeps them together because the 2002 defense was a two-man weather system with a whole crew.",
        "Lynch hit like a pirate with a plan, Safety Island as the third saint of that first title. The map paints the collision.",
        "The quarterback of the first title, Brad Johnson Grove is the quiet half of Super Bowl XXXVII. The map names him so the defense does not get to keep the whole mountain.",
        "A stadium with a ship that fires cannons, Raymond James Pirate Coliseum is the present house and the gimmick that became holy. The map paints the cannons mid-fire.",
        "A Heisman first pick who made Tampa loud, Jameis Winston Harbor is hope and chaos in pewter. The map marks the chapter honestly.",
        "Brady's last title was a Buccaneers title, Tom Brady Tampa Bay Peak as a borrowed emperor who hung a second banner. The map keeps the 12 in pewter.",
        "A championship in their own building, Super Bowl LV Home Crown is the rare February that happened on the home ship. The map paints the cannons and the home crowd.",
        "Evans is the present iron receiver, Receiving Rivers as the constant who outlasted quarterbacks and still got first downs. The map gives him the most water of the modern crew.",
        "David has been the defensive constant, Linebacker Ridge as the man who kept the pirate defense looking like a plan. The map names him so the 2010s have a spine.",
        "The present quarterback of the pewter, Baker Mayfield Present Harbor is the newest hand on a proud and strange quarterback tradition. The map leaves the water open.",
        "The bay, the skyway, and a pirate ship sit on the map because Tampa is a specific Gulf city. Civic Shores keep the water and the bridge.",
        "Cannons that fire after every score, Pewter Cannon Grove is the civic instrument this franchise invented. The map paints the smoke.",
        "Skull and swords on the horizon, Buccaneer Memorial Shores are the logo as a warning. The map keeps the flag.",
        "The civic instruction after a touchdown, Fire the Cannons Corridor is a sentence the city already knows how to shout. The map letters it on the road to the ship.",
        "Two crowns, and a ship that still sails. Pirate Legacy Horizon is the next time the cannons fire in February.",
    ],
    "cardinals": [
        "A charter NFL club older than most of the league, 1920 Chicago Cardinals Birth Cradle is the oldest bird on this whole walk. The map paints a red bird in a city that later belonged to Bears.",
        "Borrowed baseball parks in the leather-helmet years, Comiskey / Wrigley Rental Harbors are the first nests that were never really home. The map keeps the rent receipts.",
        "The family that kept the bird alive, Charles Bidwill Ownership Crown is continuity as a stubbornness. The map marks the owners because the Cardinals are a century-long argument they refused to drop.",
        "The last title, still the mountain in the desert, 1947 Championship Peak is a Chicago championship that Arizona still has to climb toward. The map does not move the mountain just because the bird moved.",
        "A Midwest chapter under the Arch, St. Louis Arrival Plains are the middle city in a three-city life. The map keeps the Arch so the desert does not erase the river.",
        "Anderson ran the Cardinals into relevance, Ottis Anderson Power River as the rushing identity of the St. Louis years. The map gives him water under the Arch.",
        "The bird landed in the desert, 1988 Phoenix Arrival Harbor as the third founding. The map paints saguaros and a red bird that had already lived two lives.",
        "Fitz is the franchise's greatest player, Larry Fitzgerald Receiving Rivers as the hands that made Arizona a football place. The map gives him the most water because Bird Gang still does.",
        "Warner made a Super Bowl out of a desert, Kurt Warner Desert Pocket as a quarterback resurrection in red. The map paints the Super Bowl lights against a saguaro dusk.",
        "James Harrison's return ended the dream, Super Bowl XLIII Heartbreak Vale as the night the oldest franchise came a play from a new crown. The map marks the return.",
        "Boldin was the tough complement to Fitz, Anquan Boldin Grove as the physical half of those late-2000s Sundays. The map keeps the contested catches.",
        "A retractable-roof bowl in a sea of saguaros, State Farm Stadium Desert Coliseum is the present nest. The map paints the roof open over the desert.",
        "Pete covered the desert sideline, Patrick Peterson Shutdown Island as the shutdown corner of the 2010s. The map gives him a closed country of sand.",
        "Palmer's late-career Cardinals years were real, Carson Palmer Ridge as a quarterback who made January look possible again. The map marks the almost.",
        "Murray is the present dual-threat bird, Kyler Murray Dual-Threat Harbor as the newest red shirt who can run the desert. The map leaves the harbor open.",
        "The next great receiver is already on the map, Marvin Harrison Jr. Present Grove as a name that arrived with history attached. The map paints the present tense.",
        "Camelback, saguaros, and the Phoenix skyline sit on the map because Arizona is a specific light, not a generic desert sticker. Civic Shores keep the red rock.",
        "A civic nickname painted in red, Bird Gang Civic Corridor is the instruction this franchise asked the valley to shout. The map letters it on the freeway.",
        "A red bird that has lived in three cities, Cardinal Memorial Grove is the logo as a survivor. The map keeps all three nests in the story.",
        "The oldest franchise still hunting a new crown. Red Bird Horizon is the next title a century of Sundays still owes the bird.",
    ],
    "49ers": [
        "1946, a miner club in scarlet and gold, AAFC Gold Rush Cradle is the Bay inventing a football identity from a Gold Rush nickname. The map paints the first SF against the Gate.",
        "The old wooden bowl in the park, Kezar Stadium Harbor is the first nest, a house the Faithful still talk about like a childhood. The map keeps the wood and the fog.",
        "Four names that still mean 1950s gold, Million Dollar Backfield Plains are the first 49ers offense that looked like a finished idea. The map paints the four as one weather.",
        "Tittle's years before New York, Y.A. Tittle Signal Tower is the original San Francisco arm. The map names him so Montana is not the first passer on the walk.",
        "Clark over Jones, 1981, The Catch Candlestick Peak is the play that invented the modern 49ers. The map paints the leap because the Faithful still see it with their eyes closed.",
        "The offense that remade the league, Bill Walsh West Coast Citadel is a coaching mountain the whole sport still lives on. The map paints the clipboard as a founding document.",
        "Montana never looked hurried, Joe Montana Cool Pocket as the quarterback who made Super Bowls look like a tempo. The map gives him the calmest air on this walk.",
        "The greatest receiver, period, Jerry Rice Receiving Rivers are yards after catch as geography. The map gives him the most water because the record book still does.",
        "Lott hit like the Bay wind, Ronnie Lott Secondary Fortress as the violent half of the first dynasty. The map does not soften the collisions.",
        "The first of five, Super Bowl XVI First Crown is the night the Gold Rush became a Super Bowl color. The map paints the first Lombardi in scarlet.",
        "Marino met Montana, Super Bowl XIX Repeat Summit is the second crown and a passing argument the West Coast won. The map marks Miami as the visiting weather.",
        "The last-minute drive, Super Bowl XXIII Drive Shore is Montana as a two-minute proverb. The map paints the last throws against a Cincinnati dusk.",
        "A wrecking-ball title, Super Bowl XXIV Blowout Peak is the fourth crown as a rout. The map keeps the score because the Faithful still enjoy the number.",
        "Young finally got his crown, Steve Young Left-Handed Ridge is the fifth Lombardi and a quarterback who had waited in the coolest shadow in the sport. The map gives him his own mountain.",
        "The fifth Lombardi, Super Bowl XXIX Dynasty Close is the end of the first gold-rush empire. The map paints five trophies because the Bay still counts that way.",
        "Wind that was a twelfth man, Candlestick Wind Arena is the house of The Catch and the dynasty. The map keeps the wind. The Faithful still feel it.",
        "The South Bay palace, Levi's Stadium Silicon Coliseum is the present house, a new nest the Faithful had to learn. The map paints the hills and the scarlet.",
        "The present architect, Kyle Shanahan Playbook Citadel is the newest West Coast mountain. The map marks the clipboard because the offense still looks like a Walsh grandson.",
        "The last pick who started January runs, Brock Purdy Mr. Irrelevant Harbor is the strangest present-tense 49ers story and a real one. The map leaves him the keys to the next climb.",
        "The bridge and the cable cars sit on the map because the Bay is a specific gold light. Golden Gate Legacy Shores are the last line: Faithful to the Bay.",
    ],
    "rams": [
        "1936, a lake-city origin, Cleveland Birth Cradle is the first ram before the horns went west. The map paints a Midwestern beginning so Los Angeles does not look like the only hometown.",
        "The last Midwestern crown, 1945 Championship Frozen Field is a title the franchise won before it became a Pacific idea. The map keeps the snow.",
        "The first NFL team on the Pacific, Los Angeles Arrival Harbor is the day the league found Hollywood. The map paints the horns against a palm dusk.",
        "Reintegration of the modern NFL, Washington and Strode Gates are the map's most important civil landmark. The walk does not treat this as a sidebar. The league changed here.",
        "Jones, Olsen, Lundy, Grier: Fearsome Foursome Pass-Rush Canyon is the 1960s front that made the horns look like a warning. The map paints four names as one cliff.",
        "The face of the near-miss 1960s, Roman Gabriel Signal Tower is the original Los Angeles ram quarterback as a civic face. The map names him so the later Super Bowls have an ancestor.",
        "Fourteen straight Pro Bowls, Merlin Olsen Ridge is the trench as a finished science. The map gives him a mountain because the Foursome needs a highest peak.",
        "He named the sack, Deacon Jones Sack Plains as the pass rusher who invented the word the league still uses. The map paints the quarterback on the ground on purpose.",
        "Bradshaw's Steelers, Super Bowl XIV Heartbreak Vale is the first February that got away in Los Angeles. The map marks Pittsburgh as the wrong weather.",
        "Goggles and a 2,105-yard season, Eric Dickerson Lightning Road is the rushing record as a ram in sunglasses. The map gives him a road that still looks too fast.",
        "A broken leg and a playoff start, Jack Youngblood Iron Will is toughness the franchise still uses as a definition. The map paints the brace.",
        "The owner of the St. Louis chapter, Georgia Frontiere Crown is the middle city in a three-city life. The map marks her so the Greatest Show has a landlord.",
        "Warner, Holt, Bruce: Greatest Show on Turf Arena is the St. Louis offense as a circus the league could not defend. The map paints the dome as a theater.",
        "One yard the other way, Super Bowl XXXIV Summit is the first Super Bowl the horns kept. The map paints the last tackle and the trophy in the same light.",
        "Brady's first title, Rams heartbreak, Super Bowl XXXVI Upset Vale is the night the Greatest Show met the beginning of a dynasty. The map marks New England as the new weather.",
        "2016, the horns came home, Return to Los Angeles Harbor is the third founding. The map paints the Hollywood sign and a ram that already knew the freeways.",
        "The greatest interior rusher, Aaron Donald Disruptor Peak is the defensive mountain of the modern return. The map paints the wreckage in the backfield.",
        "The present coach, Sean McVay Playbook Citadel is the offensive architect of the second Los Angeles empire. The map marks the headset.",
        "A title in their own building, Super Bowl LVI SoFi Crown is the night the horns won at home. The map paints the spaceship and the yellow horns in the same glow.",
        "Hollywood light and a spaceship stadium, SoFi Stadium Horizon is the present house and the last line: the horns are always home.",
    ],
    "seahawks": [
        "A Pacific Northwest expansion club in blue and green, 1976 Expansion Birth Cradle is a rainy invention that immediately found a voice. The map paints the first seahawk over the Sound.",
        "A concrete mushroom that invented 12th-man noise, Kingdome Harbor is the first nest, a roof that learned to roar. The map keeps the concrete sky.",
        "Largent was the first Seahawk in Canton, Receiving Rivers as the original skill saint. The map names him so the later Legion has a source in the passing game.",
        "Tez wrecked the 1990s interior, Cortez Kennedy Tackle Fortress as the defensive mountain of the quiet years. The map keeps the tackles.",
        "The first conference title game, 1983 AFC Title Peak is the first time the hawk looked grown. The map marks the almost.",
        "Jones was a dancing mountain at left tackle, Walter Jones Twin Ridges as the blind side of the Holmgren years. The map gives him a range because the film still looks unfair.",
        "Holmgren brought Super Bowl structure north, Mike Holmgren Rebuild Citadel as the coach who made Seattle a January city. The map marks the clipboard.",
        "Hasselbeck's we-want-the-ball years, Matt Hasselbeck Signal Tower as the quarterback who made the 2000s loud. The map keeps the dare.",
        "A Super Bowl that Seattle still argues, Super Bowl XL Heartbreak Vale is the first February, marked with the city's remaining objections. The map records the game and the argument.",
        "The loudest regular-season house in football, Lumen Field 12s Coliseum is the present nest, a bowl that registers as a seismic event. The map paints the crowd as geography.",
        "Sherman, Chancellor, Thomas, and Browner, Legion of Boom Fortress is the 2010s secondary as a wall with opinions. The map paints four names as one weather system.",
        "Beast Mode was a civic verb, Marshawn Lynch Beast Mode River as a run that became a proverb on the Super Bowl sideline. The map gives him water and a stiff-arm.",
        "Wilson made January a Seattle habit, Russell Wilson Harbor as the quarterback of the first Lombardi and the almost that followed. The map keeps both.",
        "A 43-8 wrecking of Denver, Super Bowl XLVIII First Crown is the night the 12s became a champion. The map paints the parade in action green.",
        "One yard, one throw, a ghost story, Super Bowl XLIX Goal-Line Vale is the play Seattle still sees with its eyes closed. The map marks the goal line and does not decorate it.",
        "Compete is still the house rule, Pete Carroll Competition Citadel as a coaching mountain that outlasted the first title. The map marks the practice-field law.",
        "Metcalf is the present deep threat, DK Metcalf Receiving Lightning as the newest hawk who makes the sideline look too short. The map paints the stride.",
        "Space Needle, market, ferry, and rain sit on the map because Seattle is a specific wet light. Civic Shores keep the needle and the water.",
        "The flag that means the crowd is the extra player, 12th Man Flag Peak is the civic invention this franchise named and then lived inside. The map letters 12 on the mountain.",
        "Go Hawks is the last line on the map. Hawk Legacy Horizon is the second crown the 12s are still loud enough to ask for.",
    ],
}
